// Generated by registry/generate-dex-catalog.mjs. Do not edit.

package erpc

func dexString(value string) *string { return &value }

type DexDeployment struct {
	DexDeploymentID           string
	ProtocolID                string
	Name                      string
	ChainID                   string
	ProgramAddress            string
	AdapterKind               string
	Status                    string
	ReplacedByDexDeploymentID *string
}
type PoolAdapter struct {
	Kind           string
	FeeNumerator   *string
	FeeDenominator *string
}
type PoolDefinition struct {
	PoolDefinitionID           string
	DexDeploymentID            string
	ChainID                    string
	Address                    string
	Token0DeploymentID         string
	Token1DeploymentID         string
	Adapter                    PoolAdapter
	Status                     string
	ReplacedByPoolDefinitionID *string
}
type NativeWrapDefinition struct {
	NativeWrapDefinitionID   string
	ChainID                  string
	NativeTokenDeploymentID  string
	WrappedTokenDeploymentID string
	Status                   string
}
type DexAlias struct {
	Namespace        string
	Name             string
	DexDeploymentID  *string
	PoolDefinitionID *string
}

const DexCatalogVersion = "1.0.0"
const DexCatalogAsOfDate = "2026-09-15"
const DexCatalogContentDigest = "fb6aa6d3195e6f9de97400e19fa12a4f8df9e8df63596400a1f1131816208dba"

func DexChainIDs() map[string]string {
	return map[string]string{
		"ethereum":   "eip155:1",
		"solana":     "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
		"avalancheC": "eip155:43114",
	}
}
func DexDeployments() []DexDeployment {
	return []DexDeployment{
		{DexDeploymentID: "dex-deployment-0001", ProtocolID: "uniswap-v2", Name: "Uniswap V2", ChainID: "eip155:1", ProgramAddress: "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f", AdapterKind: "evm-constant-product-v2", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0002", ProtocolID: "lfj-legacy-constant-product", Name: "LFJ legacy constant-product (Joe V1)", ChainID: "eip155:43114", ProgramAddress: "0x9ad6c38be94206ca50bb0d90783181662f0cfa10", AdapterKind: "evm-constant-product-v2", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0003", ProtocolID: "orca-whirlpools", Name: "Orca Whirlpools", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", ProgramAddress: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc", AdapterKind: "solana-orca-whirlpool", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0004", ProtocolID: "raydium-clmm", Name: "Raydium CLMM", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", ProgramAddress: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK", AdapterKind: "solana-raydium-clmm", Status: "active", ReplacedByDexDeploymentID: nil},
	}
}
func PoolDefinitions() []PoolDefinition {
	return []PoolDefinition{
		{PoolDefinitionID: "discovered-pool-11edd8516008078d92331a5ee0466fcb8400b69b56d418e566722e7d2c8c08cd", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0x43ae24960e5534731fc831386c07755a2dc33d47", Token0DeploymentID: "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-1568e761c62f7dc58207a77f2dc32153805efe03a8d9cce9366ce68efdf276c4", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xd5a37dc5c9a396a03dd1136fc76a1a02b1c88ffa", Token0DeploymentID: "discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-1b98a5f24a364e05b3d56a9702c3560fc3a71f84b2195c486cfc5f8a956cc0b7", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xc2adda861f89bbb333c90c492cb837741916a225", Token0DeploymentID: "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-3c1e38d02092d16e396d2f3a22b2bfae55246a1c566831d31f211670e45bd562", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xed8cbd9f0ce3c6986b22002f03c6475ceb7a6256", Token0DeploymentID: "deployment-0004", Token1DeploymentID: "discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-3f840a40991e755e42d242188bd8deb85cd5b9655308269b00c220f5237710cf", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xfe15c2695f1f920da45c30aae47d11de51007af9", Token0DeploymentID: "discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-5d7aa6a767a0c6ea9ddeb06d1289bd12d85018935d5b25724b165dc8b9832252", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0x48f7c83c29e5ecea926d8169864d8cd022deaf3c", Token0DeploymentID: "discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-627bab60dada7ccaf8877b4e685b841380283adfcd7a79c2a7c9580e73279411", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xaef16913b6c50ebcf627a394921f306985fc8604", Token0DeploymentID: "discovered-token-de17c35bf41345a60acbabfcc00e8108b2c058299fcb70416e9e15749f22220e", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-6428a1e5da293b2ef62027ec823ba27532219a40784def3930feee56a623b809", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xa2107fa5b38d9bbd2c461d6edf11b11a50f6b974", Token0DeploymentID: "deployment-0057", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-85f07be87c0b9be964c35ba69e421c1a611a9208bcd31ff56b645dd30cd7f68a", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xb27de0ba2abfbfdf15667a939f041b52118af5ba", Token0DeploymentID: "discovered-token-4712886cee128f138bba49725f5df0c310125ac43949b14c0edafcd90ff0d545", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-866f890448d13c078e217a894ebd47430da5941fe5bff7e382fc095916b4614d", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xb6909b960dbbe7392d405429eb2b3649752b4838", Token0DeploymentID: "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-8ee383c33ce263c33d72015ed1d41841d11eb7de663aeb314c14447248b6522b", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852", Token0DeploymentID: "deployment-0002", Token1DeploymentID: "deployment-0014", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-90805f8995c1d0b85a45fcd4587928a00066b1f14407baee4e8ed1b634c07804", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0x55d5c232d921b9eaa6b37b5845e439acd04b4dba", Token0DeploymentID: "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-9e4ed76f76904a4ae271946bb1a4b2dc7428e343040b05a42707071bbfac9462", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0x6f3a0c89f611ef5dc9d96650324ac633d02265d3", Token0DeploymentID: "deployment-0058", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-a2480f3d4ea5ce12252126acf64b174b9fe678b0f0fda8936a12fef180ae08cd", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xa389f9430876455c36478deea9769b7ca4e3ddb1", Token0DeploymentID: "deployment-0018", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-a7f9e600a86951f40472ff779fae467db8a6bbbc6076356058f427e97d4ae429", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xa478c2975ab1ea89e8196811f51a7b7ade33eb11", Token0DeploymentID: "deployment-0019", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-ae8a33a46b624bc85796b9038b9cedaa172b92052b6f5a6eee80de879c58fa75", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xc5be99a02c6857f9eac67bbce58df5572498f40c", Token0DeploymentID: "deployment-0002", Token1DeploymentID: "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-b8f972f8bae36c82b51ed2aeed070d3ef3e7642e2a708c7d3c0c134e6e1946ed", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0x11b1f53204d03e5529f09eb3091939e4fd8c9cf3", Token0DeploymentID: "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-d87fccc735fcb198dbfd3120db47630db1c614f13b3cedbe9f7a0d7efc61c4df", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xa32523371390b0cc4e11f6bb236ecf4c2cdea101", Token0DeploymentID: "discovered-token-23a03dcf2efbe86795f325e3f649738ef7315dfd1f6039c347c515c9c9c612bd", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-e702b0cb56528418b4ce089dfc001c6241c94e92aabde72f1a340c4601541780", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xbb2b8038a1640196fbe3e38816f3e67cba72d940", Token0DeploymentID: "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-ece9088cf38944438897ff9fb2a1abc6855a687b5a3f0d6ab98dfe06c1a6dfef", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0x454e67025631c065d3cfad6d71e6892f74487a15", Token0DeploymentID: "deployment-0059", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-fb02e85806cd907920126af935137b0775a858ddf04a28d7ca144f761fd7579e", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xb6a00cead355d1ec492fd72e1d79199c347a74b5", Token0DeploymentID: "discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804", Token1DeploymentID: "deployment-0004", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "discovered-pool-fea726b2c744d8da56acd8c0801829e2054b7292fd96aa74eea9e732d5b96c40", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0x819f3450da6f110ba6ea52195b3beafa246062de", Token0DeploymentID: "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0001", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc", Token0DeploymentID: "deployment-0008", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0002", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xf4003f4efbe8691b60249e6afbd307abe7758adb", Token0DeploymentID: "deployment-0004", Token1DeploymentID: "deployment-0009", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0003", DexDeploymentID: "dex-deployment-0003", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", Address: "FgH1dEvyRQoAqJjbUzzKVoM1HYdxTqPwjEF82kDH1kVe", Token0DeploymentID: "deployment-0006", Token1DeploymentID: "deployment-0013", Adapter: PoolAdapter{Kind: "solana-orca-whirlpool", FeeNumerator: nil, FeeDenominator: nil}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0004", DexDeploymentID: "dex-deployment-0004", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", Address: "AwaVyGAF3N6K4YRUJk55Ui1GquKhKdD6vTCmVvCzXpKf", Token0DeploymentID: "deployment-0006", Token1DeploymentID: "deployment-0013", Adapter: PoolAdapter{Kind: "solana-raydium-clmm", FeeNumerator: nil, FeeDenominator: nil}, Status: "active", ReplacedByPoolDefinitionID: nil},
	}
}
func NativeWrapDefinitions() []NativeWrapDefinition {
	return []NativeWrapDefinition{
		{NativeWrapDefinitionID: "native-wrap-0001", ChainID: "eip155:1", NativeTokenDeploymentID: "deployment-0001", WrappedTokenDeploymentID: "deployment-0002", Status: "active"},
		{NativeWrapDefinitionID: "native-wrap-0002", ChainID: "eip155:43114", NativeTokenDeploymentID: "deployment-0003", WrappedTokenDeploymentID: "deployment-0004", Status: "active"},
		{NativeWrapDefinitionID: "native-wrap-0003", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", NativeTokenDeploymentID: "deployment-0005", WrappedTokenDeploymentID: "deployment-0006", Status: "active"},
	}
}
func DexAliases() []DexAlias {
	return []DexAlias{
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_1568E761C62F7DC5", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_1568E761C62F7DC5)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_3C1E38D02092D16E", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_3C1E38D02092D16E)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_3F840A40991E755E", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_3F840A40991E755E)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_5D7AA6A767A0C6EA", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_5D7AA6A767A0C6EA)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_9E4ED76F76904A4A", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_9E4ED76F76904A4A)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_A2480F3D4EA5CE12", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_A2480F3D4EA5CE12)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_ECE9088CF3894443", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_ECE9088CF3894443)},
		{Namespace: "avalancheC", Name: "DISCOVERED_POOL_FB02E85806CD9079", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCDISCOVERED_POOL_FB02E85806CD9079)},
		{Namespace: "avalancheC", Name: "LFJ_LEGACY", DexDeploymentID: dexString(DexAvalancheCLFJ_LEGACY), PoolDefinitionID: nil},
		{Namespace: "avalancheC", Name: "LFJ_LEGACY_WAVAX_USDC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCLFJ_LEGACY_WAVAX_USDC)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_11EDD8516008078D", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_11EDD8516008078D)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_1B98A5F24A364E05", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_1B98A5F24A364E05)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_627BAB60DADA7CCA", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_627BAB60DADA7CCA)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_6428A1E5DA293B2E", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_6428A1E5DA293B2E)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_85F07BE87C0B9BE9", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_85F07BE87C0B9BE9)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_866F890448D13C07", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_866F890448D13C07)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_8EE383C33CE263C3", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_8EE383C33CE263C3)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_90805F8995C1D0B8", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_90805F8995C1D0B8)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_A7F9E600A86951F4", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_A7F9E600A86951F4)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_AE8A33A46B624BC8", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_AE8A33A46B624BC8)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_B8F972F8BAE36C82", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_B8F972F8BAE36C82)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_D87FCCC735FCB198", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_D87FCCC735FCB198)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_E702B0CB56528418", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_E702B0CB56528418)},
		{Namespace: "ethereum", Name: "DISCOVERED_POOL_FEA726B2C744D8DA", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumDISCOVERED_POOL_FEA726B2C744D8DA)},
		{Namespace: "ethereum", Name: "UNISWAP_V2", DexDeploymentID: dexString(DexEthereumUNISWAP_V2), PoolDefinitionID: nil},
		{Namespace: "ethereum", Name: "UNISWAP_V2_USDC_WETH", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumUNISWAP_V2_USDC_WETH)},
		{Namespace: "solana", Name: "ORCA_WHIRLPOOLS", DexDeploymentID: dexString(DexSolanaORCA_WHIRLPOOLS), PoolDefinitionID: nil},
		{Namespace: "solana", Name: "ORCA_WHIRLPOOLS_WSOL_EURC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolSolanaORCA_WHIRLPOOLS_WSOL_EURC)},
		{Namespace: "solana", Name: "RAYDIUM_CLMM", DexDeploymentID: dexString(DexSolanaRAYDIUM_CLMM), PoolDefinitionID: nil},
		{Namespace: "solana", Name: "RAYDIUM_CLMM_WSOL_EURC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolSolanaRAYDIUM_CLMM_WSOL_EURC)},
	}
}

const PoolAvalancheCDISCOVERED_POOL_1568E761C62F7DC5 = "discovered-pool-1568e761c62f7dc58207a77f2dc32153805efe03a8d9cce9366ce68efdf276c4"
const PoolAvalancheCDISCOVERED_POOL_3C1E38D02092D16E = "discovered-pool-3c1e38d02092d16e396d2f3a22b2bfae55246a1c566831d31f211670e45bd562"
const PoolAvalancheCDISCOVERED_POOL_3F840A40991E755E = "discovered-pool-3f840a40991e755e42d242188bd8deb85cd5b9655308269b00c220f5237710cf"
const PoolAvalancheCDISCOVERED_POOL_5D7AA6A767A0C6EA = "discovered-pool-5d7aa6a767a0c6ea9ddeb06d1289bd12d85018935d5b25724b165dc8b9832252"
const PoolAvalancheCDISCOVERED_POOL_9E4ED76F76904A4A = "discovered-pool-9e4ed76f76904a4ae271946bb1a4b2dc7428e343040b05a42707071bbfac9462"
const PoolAvalancheCDISCOVERED_POOL_A2480F3D4EA5CE12 = "discovered-pool-a2480f3d4ea5ce12252126acf64b174b9fe678b0f0fda8936a12fef180ae08cd"
const PoolAvalancheCDISCOVERED_POOL_ECE9088CF3894443 = "discovered-pool-ece9088cf38944438897ff9fb2a1abc6855a687b5a3f0d6ab98dfe06c1a6dfef"
const PoolAvalancheCDISCOVERED_POOL_FB02E85806CD9079 = "discovered-pool-fb02e85806cd907920126af935137b0775a858ddf04a28d7ca144f761fd7579e"
const DexAvalancheCLFJ_LEGACY = "dex-deployment-0002"
const PoolAvalancheCLFJ_LEGACY_WAVAX_USDC = "pool-0002"
const PoolEthereumDISCOVERED_POOL_11EDD8516008078D = "discovered-pool-11edd8516008078d92331a5ee0466fcb8400b69b56d418e566722e7d2c8c08cd"
const PoolEthereumDISCOVERED_POOL_1B98A5F24A364E05 = "discovered-pool-1b98a5f24a364e05b3d56a9702c3560fc3a71f84b2195c486cfc5f8a956cc0b7"
const PoolEthereumDISCOVERED_POOL_627BAB60DADA7CCA = "discovered-pool-627bab60dada7ccaf8877b4e685b841380283adfcd7a79c2a7c9580e73279411"
const PoolEthereumDISCOVERED_POOL_6428A1E5DA293B2E = "discovered-pool-6428a1e5da293b2ef62027ec823ba27532219a40784def3930feee56a623b809"
const PoolEthereumDISCOVERED_POOL_85F07BE87C0B9BE9 = "discovered-pool-85f07be87c0b9be964c35ba69e421c1a611a9208bcd31ff56b645dd30cd7f68a"
const PoolEthereumDISCOVERED_POOL_866F890448D13C07 = "discovered-pool-866f890448d13c078e217a894ebd47430da5941fe5bff7e382fc095916b4614d"
const PoolEthereumDISCOVERED_POOL_8EE383C33CE263C3 = "discovered-pool-8ee383c33ce263c33d72015ed1d41841d11eb7de663aeb314c14447248b6522b"
const PoolEthereumDISCOVERED_POOL_90805F8995C1D0B8 = "discovered-pool-90805f8995c1d0b85a45fcd4587928a00066b1f14407baee4e8ed1b634c07804"
const PoolEthereumDISCOVERED_POOL_A7F9E600A86951F4 = "discovered-pool-a7f9e600a86951f40472ff779fae467db8a6bbbc6076356058f427e97d4ae429"
const PoolEthereumDISCOVERED_POOL_AE8A33A46B624BC8 = "discovered-pool-ae8a33a46b624bc85796b9038b9cedaa172b92052b6f5a6eee80de879c58fa75"
const PoolEthereumDISCOVERED_POOL_B8F972F8BAE36C82 = "discovered-pool-b8f972f8bae36c82b51ed2aeed070d3ef3e7642e2a708c7d3c0c134e6e1946ed"
const PoolEthereumDISCOVERED_POOL_D87FCCC735FCB198 = "discovered-pool-d87fccc735fcb198dbfd3120db47630db1c614f13b3cedbe9f7a0d7efc61c4df"
const PoolEthereumDISCOVERED_POOL_E702B0CB56528418 = "discovered-pool-e702b0cb56528418b4ce089dfc001c6241c94e92aabde72f1a340c4601541780"
const PoolEthereumDISCOVERED_POOL_FEA726B2C744D8DA = "discovered-pool-fea726b2c744d8da56acd8c0801829e2054b7292fd96aa74eea9e732d5b96c40"
const DexEthereumUNISWAP_V2 = "dex-deployment-0001"
const PoolEthereumUNISWAP_V2_USDC_WETH = "pool-0001"
const DexSolanaORCA_WHIRLPOOLS = "dex-deployment-0003"
const PoolSolanaORCA_WHIRLPOOLS_WSOL_EURC = "pool-0003"
const DexSolanaRAYDIUM_CLMM = "dex-deployment-0004"
const PoolSolanaRAYDIUM_CLMM_WSOL_EURC = "pool-0004"
