// Generated by registry/generate-dex-catalog.mjs. Do not edit.

package erpc

func dexString(value string) *string { return &value }

type DexDeployment struct {
	DexDeploymentID           string
	ProtocolID                string
	Name                      string
	ChainID                   string
	ProgramAddress            string
	AdapterKind               string
	Status                    string
	ReplacedByDexDeploymentID *string
}
type PoolAdapter struct {
	Kind           string
	FeeNumerator   *string
	FeeDenominator *string
}
type PoolDefinition struct {
	PoolDefinitionID           string
	DexDeploymentID            string
	ChainID                    string
	Address                    string
	Token0DeploymentID         string
	Token1DeploymentID         string
	Adapter                    PoolAdapter
	Status                     string
	ReplacedByPoolDefinitionID *string
}
type NativeWrapDefinition struct {
	NativeWrapDefinitionID   string
	ChainID                  string
	NativeTokenDeploymentID  string
	WrappedTokenDeploymentID string
	Status                   string
}
type DexAlias struct {
	Namespace        string
	Name             string
	DexDeploymentID  *string
	PoolDefinitionID *string
}

const DexCatalogVersion = "1.0.0"
const DexCatalogAsOfDate = "2026-09-15"
const DexCatalogContentDigest = "002c05c3c2d5d3917f73a5c2e7b55af9ceb9a682fb49ae28d2421046ee2faa50"

func DexChainIDs() map[string]string {
	return map[string]string{
		"ethereum":   "eip155:1",
		"solana":     "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
		"avalancheC": "eip155:43114",
	}
}
func DexDeployments() []DexDeployment {
	return []DexDeployment{
		{DexDeploymentID: "dex-deployment-0001", ProtocolID: "uniswap-v2", Name: "Uniswap V2", ChainID: "eip155:1", ProgramAddress: "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f", AdapterKind: "evm-constant-product-v2", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0002", ProtocolID: "lfj-legacy-constant-product", Name: "LFJ legacy constant-product (Joe V1)", ChainID: "eip155:43114", ProgramAddress: "0x9ad6c38be94206ca50bb0d90783181662f0cfa10", AdapterKind: "evm-constant-product-v2", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0003", ProtocolID: "orca-whirlpools", Name: "Orca Whirlpools", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", ProgramAddress: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc", AdapterKind: "solana-orca-whirlpool", Status: "active", ReplacedByDexDeploymentID: nil},
		{DexDeploymentID: "dex-deployment-0004", ProtocolID: "raydium-clmm", Name: "Raydium CLMM", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", ProgramAddress: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK", AdapterKind: "solana-raydium-clmm", Status: "active", ReplacedByDexDeploymentID: nil},
	}
}
func PoolDefinitions() []PoolDefinition {
	return []PoolDefinition{
		{PoolDefinitionID: "pool-0001", DexDeploymentID: "dex-deployment-0001", ChainID: "eip155:1", Address: "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc", Token0DeploymentID: "deployment-0008", Token1DeploymentID: "deployment-0002", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0002", DexDeploymentID: "dex-deployment-0002", ChainID: "eip155:43114", Address: "0xf4003f4efbe8691b60249e6afbd307abe7758adb", Token0DeploymentID: "deployment-0004", Token1DeploymentID: "deployment-0009", Adapter: PoolAdapter{Kind: "evm-constant-product-v2", FeeNumerator: dexString("3"), FeeDenominator: dexString("1000")}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0003", DexDeploymentID: "dex-deployment-0003", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", Address: "FgH1dEvyRQoAqJjbUzzKVoM1HYdxTqPwjEF82kDH1kVe", Token0DeploymentID: "deployment-0006", Token1DeploymentID: "deployment-0013", Adapter: PoolAdapter{Kind: "solana-orca-whirlpool", FeeNumerator: nil, FeeDenominator: nil}, Status: "active", ReplacedByPoolDefinitionID: nil},
		{PoolDefinitionID: "pool-0004", DexDeploymentID: "dex-deployment-0004", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", Address: "AwaVyGAF3N6K4YRUJk55Ui1GquKhKdD6vTCmVvCzXpKf", Token0DeploymentID: "deployment-0006", Token1DeploymentID: "deployment-0013", Adapter: PoolAdapter{Kind: "solana-raydium-clmm", FeeNumerator: nil, FeeDenominator: nil}, Status: "active", ReplacedByPoolDefinitionID: nil},
	}
}
func NativeWrapDefinitions() []NativeWrapDefinition {
	return []NativeWrapDefinition{
		{NativeWrapDefinitionID: "native-wrap-0001", ChainID: "eip155:1", NativeTokenDeploymentID: "deployment-0001", WrappedTokenDeploymentID: "deployment-0002", Status: "active"},
		{NativeWrapDefinitionID: "native-wrap-0002", ChainID: "eip155:43114", NativeTokenDeploymentID: "deployment-0003", WrappedTokenDeploymentID: "deployment-0004", Status: "active"},
		{NativeWrapDefinitionID: "native-wrap-0003", ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", NativeTokenDeploymentID: "deployment-0005", WrappedTokenDeploymentID: "deployment-0006", Status: "active"},
	}
}
func DexAliases() []DexAlias {
	return []DexAlias{
		{Namespace: "avalancheC", Name: "LFJ_LEGACY", DexDeploymentID: dexString(DexAvalancheCLFJ_LEGACY), PoolDefinitionID: nil},
		{Namespace: "avalancheC", Name: "LFJ_LEGACY_WAVAX_USDC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolAvalancheCLFJ_LEGACY_WAVAX_USDC)},
		{Namespace: "ethereum", Name: "UNISWAP_V2", DexDeploymentID: dexString(DexEthereumUNISWAP_V2), PoolDefinitionID: nil},
		{Namespace: "ethereum", Name: "UNISWAP_V2_USDC_WETH", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolEthereumUNISWAP_V2_USDC_WETH)},
		{Namespace: "solana", Name: "ORCA_WHIRLPOOLS", DexDeploymentID: dexString(DexSolanaORCA_WHIRLPOOLS), PoolDefinitionID: nil},
		{Namespace: "solana", Name: "ORCA_WHIRLPOOLS_WSOL_EURC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolSolanaORCA_WHIRLPOOLS_WSOL_EURC)},
		{Namespace: "solana", Name: "RAYDIUM_CLMM", DexDeploymentID: dexString(DexSolanaRAYDIUM_CLMM), PoolDefinitionID: nil},
		{Namespace: "solana", Name: "RAYDIUM_CLMM_WSOL_EURC", DexDeploymentID: nil, PoolDefinitionID: dexString(PoolSolanaRAYDIUM_CLMM_WSOL_EURC)},
	}
}

const DexAvalancheCLFJ_LEGACY = "dex-deployment-0002"
const PoolAvalancheCLFJ_LEGACY_WAVAX_USDC = "pool-0002"
const DexEthereumUNISWAP_V2 = "dex-deployment-0001"
const PoolEthereumUNISWAP_V2_USDC_WETH = "pool-0001"
const DexSolanaORCA_WHIRLPOOLS = "dex-deployment-0003"
const PoolSolanaORCA_WHIRLPOOLS_WSOL_EURC = "pool-0003"
const DexSolanaRAYDIUM_CLMM = "dex-deployment-0004"
const PoolSolanaRAYDIUM_CLMM_WSOL_EURC = "pool-0004"
