// Generated by registry/generate-token-rankings.mjs. Do not edit.
package erpc

func tokenRankingString(value string) *string { return &value }

type TokenRanking struct {
	Rank              int
	ChainID           string
	DeploymentIDs     []string
	Metric            string
	ValueNumerator    string
	ValueDenominator  string
	QuoteCurrency     string
	QuoteDeploymentID *string
	ObservedAt        string
	SourceID          string
	SourceAssetID     *string
}
type TokenRankingCoverage struct {
	ChainID             string
	TotalDeployments    int
	RankedDeployments   int
	UnrankedDeployments int
	ObservedAt          *string
}
type TokenRankingSnapshotMetadata struct {
	SchemaVersion int
	Metric        *string
	AsOf          *string
	ContentDigest string
	Status        string
	Coverage      []TokenRankingCoverage
	SourceIDs     []string
}

const TokenRankingsSchemaVersion = 1
const TokenRankingsMetric = "onchain-total-supply-value-native"
const TokenRankingsAsOf = "2026-10-03T09:01:11Z"
const TokenRankingsContentDigest = "86d3091bc7282438a5f4ea64a0aec64f676b3f84f8f6257807ebb09536da0f56"
const TokenRankingsStatus = "partial"

var tokenRankingsMetricValue = tokenRankingString("onchain-total-supply-value-native")
var tokenRankingsAsOfValue = tokenRankingString("2026-10-03T09:01:11Z")
var tokenRankingsCoverage = []TokenRankingCoverage{{ChainID: "eip155:1", TotalDeployments: 34, RankedDeployments: 9, UnrankedDeployments: 25, ObservedAt: tokenRankingString("2026-10-03T09:01:11Z")}, {ChainID: "eip155:43114", TotalDeployments: 17, RankedDeployments: 0, UnrankedDeployments: 17, ObservedAt: tokenRankingString("2026-10-03T09:16:06Z")}, {ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", TotalDeployments: 19, RankedDeployments: 0, UnrankedDeployments: 19, ObservedAt: tokenRankingString("2026-10-03T09:16:06Z")}}
var tokenRankingsSourceIDs = []string{"rpc-avalanche-c-mainnet", "rpc-ethereum-mainnet", "rpc-solana-mainnet"}
var tokenRankings = []TokenRanking{
	{Rank: 1, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0014"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "82897803772028321241209445971403271667", ValueDenominator: "2513773972317", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 2, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0008"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "95712397005185480436024638278930146915", ValueDenominator: "5233354281586", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 3, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0057"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "147042827976068449985000000000000000000000000000", ValueDenominator: "28193659082725486506453", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 4, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "6736725645272025482221303972010436", ValueDenominator: "1835385151", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 5, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0019"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "8135924368025922081144629206814356937640684129076", ValueDenominator: "4738013330014906832924153", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 6, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "37652529553157038666753415959350493870778863168", ValueDenominator: "451936961487684764877311", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 7, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "25727867450908444944540929855320344741753198", ValueDenominator: "399008275283338274845", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 8, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "2557335894586116041850000000000000000000000000", ValueDenominator: "47728403838468112718809", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 9, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "504222095930248604082409597038287075256", ValueDenominator: "25161603337018519", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-10-03T09:01:11Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
}

func cloneTokenRanking(value TokenRanking) TokenRanking {
	value.DeploymentIDs = append([]string(nil), value.DeploymentIDs...)
	if value.QuoteDeploymentID != nil {
		value.QuoteDeploymentID = tokenRankingString(*value.QuoteDeploymentID)
	}
	if value.SourceAssetID != nil {
		value.SourceAssetID = tokenRankingString(*value.SourceAssetID)
	}
	return value
}
func ListTokenRankings(chainID string) []TokenRanking {
	result := make([]TokenRanking, 0)
	for _, value := range tokenRankings {
		if value.ChainID == chainID {
			result = append(result, cloneTokenRanking(value))
		}
	}
	return result
}
func TokenRankingMetadata() TokenRankingSnapshotMetadata {
	coverage := make([]TokenRankingCoverage, len(tokenRankingsCoverage))
	copy(coverage, tokenRankingsCoverage)
	for index := range coverage {
		if coverage[index].ObservedAt != nil {
			coverage[index].ObservedAt = tokenRankingString(*coverage[index].ObservedAt)
		}
	}
	sourceIDs := make([]string, len(tokenRankingsSourceIDs))
	copy(sourceIDs, tokenRankingsSourceIDs)
	var metric *string
	if tokenRankingsMetricValue != nil {
		metric = tokenRankingString(*tokenRankingsMetricValue)
	}
	var asOf *string
	if tokenRankingsAsOfValue != nil {
		asOf = tokenRankingString(*tokenRankingsAsOfValue)
	}
	return TokenRankingSnapshotMetadata{SchemaVersion: 1, Metric: metric, AsOf: asOf, ContentDigest: TokenRankingsContentDigest, Status: TokenRankingsStatus, Coverage: coverage, SourceIDs: sourceIDs}
}
