// Generated by registry/generate-token-catalog.mjs. Do not edit.

package erpc

type TokenRepresentationKind string
type TokenStandard string
type TokenStatus string
type TokenChainID = string
type TokenChainId = TokenChainID

const (
	TokenRepresentationNative       TokenRepresentationKind = "native"
	TokenRepresentationIssued       TokenRepresentationKind = "issued"
	TokenRepresentationWrapped      TokenRepresentationKind = "wrapped"
	TokenRepresentationBridged      TokenRepresentationKind = "bridged"
	TokenRepresentationUnclassified TokenRepresentationKind = "unclassified"
	TokenStandardNative             TokenStandard           = "native"
	TokenStandardERC20              TokenStandard           = "erc20"
	TokenStandardSPLToken           TokenStandard           = "spl-token"
	TokenStandardSPLToken2022       TokenStandard           = "spl-token-2022"
	TokenStatusActive               TokenStatus             = "active"
	TokenStatusLegacy               TokenStatus             = "legacy"
	TokenStatusWindingDown          TokenStatus             = "winding-down"
	TokenStatusRetired              TokenStatus             = "retired"
)

type TokenAsset struct {
	AssetID                  string
	Name                     string
	RepresentationKind       TokenRepresentationKind
	StableCurrency           *string
	UnderlyingAssetID        *string
	EconomicReferenceAssetID *string
}

type TokenDeployment struct {
	DeploymentID             string
	AssetID                  string
	Name                     string
	RepresentationKind       TokenRepresentationKind
	StableCurrency           *string
	UnderlyingAssetID        *string
	EconomicReferenceAssetID *string
	ChainID                  TokenChainId
	Symbol                   string
	Decimals                 uint8
	Standard                 TokenStandard
	Address                  *string
	Status                   TokenStatus
	ReplacedByDeploymentID   *string
}

type TokenAlias struct {
	Namespace    string
	Name         string
	DeploymentID string
}

func tokenString(value string) *string { copied := value; return &copied }

const TOKEN_CATALOG_VERSION = "1.0.0"
const TOKEN_CATALOG_AS_OF_DATE = "2026-09-15"
const TOKEN_CATALOG_CONTENT_DIGEST = "40d92b9dee6fdf30d53b9ccfb826c7850fceb48992bd7ac14ae2efcd33ebc571"
const TokenEthereumChainID TokenChainID = "eip155:1"
const TokenSolanaChainID TokenChainID = "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"
const TokenAvalancheCChainID TokenChainID = "eip155:43114"

func TokenChainIDs() map[string]TokenChainID {
	return map[string]TokenChainID{
		"ethereum":   TokenEthereumChainID,
		"solana":     TokenSolanaChainID,
		"avalancheC": TokenAvalancheCChainID,
	}
}

func TokenAssets() []TokenAsset {
	return []TokenAsset{
		{
			AssetID: "asset-0001", Name: "Ether", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0002", Name: "Wrapped Ether", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0001"), EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0003", Name: "Avalanche", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0004", Name: "Wrapped AVAX", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0003"), EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0005", Name: "Solana", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0006", Name: "Wrapped SOL", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0005"), EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0007", Name: "USD Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0008", Name: "Euro Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0009", Name: "Tether USDt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0010", Name: "Tether EURt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0011", Name: "Bridged USD Coin (USDC.e)", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0007"),
		},
		{
			AssetID: "asset-0012", Name: "Dai", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0013", Name: "Sky Dollar", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0014", Name: "Bridged Sky Dollar", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0013"),
		},
		{
			AssetID: "asset-0015", Name: "PayPal USD (PYUSD)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0016", Name: "Global Dollar (USDG)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0017", Name: "Pax Dollar (USDP)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0018", Name: "USDe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0019", Name: "GHO", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0020", Name: "Bridged GHO", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0019"),
		},
		{
			AssetID: "asset-0021", Name: "First Digital USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0022", Name: "Ripple USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0023", Name: "Agora USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0024", Name: "Jupiter USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0025", Name: "JPY Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0026", Name: "Euro CoinVertible", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0027", Name: "EURAU", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0028", Name: "EUROP", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0029", Name: "GYEN", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0030", Name: "ZUSD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0031", Name: "Angle EURA", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0032", Name: "STASIS EURS", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0033", Name: "Monerium EURe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0034", Name: "Uniswap", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0035", Name: "Aave", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0036", Name: "Chainlink", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0037", Name: "Bridged Chainlink", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0036"),
		},
		{
			AssetID: "asset-0038", Name: "Trader Joe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "asset-0039", Name: "Jupiter", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5", Name: "Unclassified token at 0x0f5d2fb29fb7d3cfee444a200298f468908cc942", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692", Name: "Unclassified token at 0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804", Name: "Unclassified token at 0x02e955e93055e5a9d7fe6e9ee65126b321acef76", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5", Name: "Unclassified token at 0xc7198437980c041c805a1edcba50c1ce5db95118", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-2ad4730de37ecbe3f9219de3eaf0c5d66062ad8a4a7141f75f44122844f55305", Name: "Unclassified token at 0x8729438eb15e2c8b576fcc6aecda6a148776c0f5", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d", Name: "Unclassified token at 0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371", Name: "Unclassified token at 0x3ceeb67533e494c0dc6be579585e3c62916062e0", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-5d9e514643710480cadd0be3aedb94f01fe8cd7b5d4d1ea4556392a3a9177512", Name: "Unclassified token at 0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec", Name: "Unclassified token at 0x2b591e99afe9f32eaa6214f7b7629768c40eeb39", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6", Name: "Unclassified token at 0x0d8775f648430679a709e98d2b0cb6250d2887ef", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-7028d97cbfa0ea3ea143c41320a542a002a7c21be7a0f6e38ca8c2053789917c", Name: "Unclassified token at 0xd586e7f844cea2f87f50152665bcbc2c279d8d70", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-991aaccb7a9c45364e52c40b90f6e1cc12c38d4270f8e936f7258c8a450f2bf2", Name: "Unclassified token at 0x82fe038ea4b50f9c957da326c412ebd73462077c", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d", Name: "Unclassified token at 0x50b7545627a5162f82a992c33b87adc75187b218", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6", Name: "Unclassified token at 0xd46ba6d942050d489dbd938a2c909a5d5039a161", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395", Name: "Unclassified token at 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556", Name: "Unclassified token at 0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
		{
			AssetID: "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07", Name: "Unclassified token at 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
		},
	}
}

func TokenDeployments() []TokenDeployment {
	return []TokenDeployment{
		{
			DeploymentID: "deployment-0001", AssetID: "asset-0001", Name: "Ether", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "ETH", Decimals: 18, Standard: TokenStandard("native"),
			Address: nil, Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0002", AssetID: "asset-0002", Name: "Wrapped Ether", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0001"), EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "WETH", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0003", AssetID: "asset-0003", Name: "Avalanche", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "AVAX", Decimals: 18, Standard: TokenStandard("native"),
			Address: nil, Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0004", AssetID: "asset-0004", Name: "Wrapped AVAX", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0003"), EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "WAVAX", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0005", AssetID: "asset-0005", Name: "Solana", RepresentationKind: TokenRepresentationKind("native"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "SOL", Decimals: 9, Standard: TokenStandard("native"),
			Address: nil, Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0006", AssetID: "asset-0006", Name: "Wrapped SOL", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0005"), EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "WSOL", Decimals: 9, Standard: TokenStandard("spl-token"),
			Address: tokenString("So11111111111111111111111111111111111111112"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0007", AssetID: "asset-0006", Name: "Wrapped SOL", RepresentationKind: TokenRepresentationKind("wrapped"),
			StableCurrency: nil, UnderlyingAssetID: tokenString("asset-0005"), EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "WSOL", Decimals: 9, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("9pan9bMn5HatX4EJdBwg9VgCa7Uz5HL8N1m5D3NdXejP"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0008", AssetID: "asset-0007", Name: "USD Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDC", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0009", AssetID: "asset-0007", Name: "USD Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "USDC", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0010", AssetID: "asset-0007", Name: "USD Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "USDC", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0011", AssetID: "asset-0008", Name: "Euro Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURC", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x1abaea1f7c830bd89acc67ec4af516284b1bc33c"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0012", AssetID: "asset-0008", Name: "Euro Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "EURC", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc891eb4cbdeff6e073e859e987815ed1505c2acd"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0013", AssetID: "asset-0008", Name: "Euro Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "EURC", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0014", AssetID: "asset-0009", Name: "Tether USDt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDT", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xdac17f958d2ee523a2206206994597c13d831ec7"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0015", AssetID: "asset-0009", Name: "Tether USDt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "USDT", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0016", AssetID: "asset-0009", Name: "Tether USDt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "USDT", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0017", AssetID: "asset-0010", Name: "Tether EURt", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURT", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc581b735a1688071a1746c968e0798d642ede491"), Status: TokenStatus("retired"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0018", AssetID: "asset-0011", Name: "Bridged USD Coin (USDC.e)", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0007"),
			ChainID: TokenChainID("eip155:43114"), Symbol: "USDC.e", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664"), Status: TokenStatus("legacy"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0019", AssetID: "asset-0012", Name: "Dai", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "DAI", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x6b175474e89094c44da98b954eedeac495271d0f"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0020", AssetID: "asset-0013", Name: "Sky Dollar", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDS", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xdc035d45d973e3ec169d2276ddab16f1e407384f"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0021", AssetID: "asset-0014", Name: "Bridged Sky Dollar", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0013"),
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "USDS", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0022", AssetID: "asset-0015", Name: "PayPal USD (PYUSD)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "PYUSD", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x6c3ea9036406852006290770bedfcaba0e23a0e8"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0023", AssetID: "asset-0015", Name: "PayPal USD (PYUSD)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "PYUSD", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0024", AssetID: "asset-0016", Name: "Global Dollar (USDG)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDG", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xe343167631d89b6ffc58b88d6b7fb0228795491d"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0025", AssetID: "asset-0016", Name: "Global Dollar (USDG)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "USDG", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("2u1tszSeqZ3qBWF3uNGPFc8TzMk2tdiwknnRMWGWjGWH"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0026", AssetID: "asset-0017", Name: "Pax Dollar (USDP)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDP", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x8e870d67f660d95d5be530380d0ec0bd388289e1"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0027", AssetID: "asset-0017", Name: "Pax Dollar (USDP)", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "USDP", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("HVbpJAQGNpkgBaYBZQBR1t7yFdvaYVp2vCQQfKKEN4tM"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0028", AssetID: "asset-0018", Name: "USDe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "USDe", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x4c9edd5852cd905f086c759e8383e09bff1e68b3"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0029", AssetID: "asset-0019", Name: "GHO", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "GHO", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x40d16fc0246ad3160ccc09b8d0d3a2cd28ae6c2f"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0030", AssetID: "asset-0020", Name: "Bridged GHO", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0019"),
			ChainID: TokenChainID("eip155:43114"), Symbol: "GHO", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xfc421ad3c883bf9e7c4f42de845c4e4405799e73"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0031", AssetID: "asset-0021", Name: "First Digital USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "FDUSD", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc5f0f7b66764f6ec8c8dff7ba683102295e16409"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0032", AssetID: "asset-0021", Name: "First Digital USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "FDUSD", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("9zNQRsGLjNKwCUU5Gq5LR8beUCPzQMVMqKAi3SSZh54u"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0033", AssetID: "asset-0022", Name: "Ripple USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "RLUSD", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x8292bb45bf1ee4d140127049757c2e0ff06317ed"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0034", AssetID: "asset-0023", Name: "Agora USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "AUSD", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x00000000efe302beaa2b3e6e1b18d08d69a9012a"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0035", AssetID: "asset-0023", Name: "Agora USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "AUSD", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x00000000efe302beaa2b3e6e1b18d08d69a9012a"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0036", AssetID: "asset-0023", Name: "Agora USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "AUSD", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("AUSD1jCcCyPLybk1YnvPWsHQSrZ46dxwoMniN4N2UEB9"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0037", AssetID: "asset-0024", Name: "Jupiter USD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "JupUSD", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("JuprjznTrTSp2UFa3ZBUFgwdAmtZCq4MQCwysN55USD"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0038", AssetID: "asset-0025", Name: "JPY Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "JPYC", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xe7c3d8c9a439fede00d2600032d5db0be71c3c29"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0039", AssetID: "asset-0025", Name: "JPY Coin", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "JPYC", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xe7c3d8c9a439fede00d2600032d5db0be71c3c29"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0040", AssetID: "asset-0026", Name: "Euro CoinVertible", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURCV", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x5f7827fdeb7c20b443265fc2f40845b715385ff2"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0041", AssetID: "asset-0026", Name: "Euro CoinVertible", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "EURCV", Decimals: 2, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("DghpMkatCiUsofbTmid3M3kAbDTPqDwKiYHnudXeGG52"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0042", AssetID: "asset-0027", Name: "EURAU", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURAU", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x4933a85b5b5466fbaf179f72d3de273c287ec2c2"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0043", AssetID: "asset-0027", Name: "EURAU", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "EURAU", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("9pCWprxbZMW2rYSMhPTeoyLMV2sN2WJqshdT7DQVt6hS"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0044", AssetID: "asset-0028", Name: "EUROP", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EUROP", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x888883b5f5d21fb10dfeb70e8f9722b9fb0e5e51"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0045", AssetID: "asset-0028", Name: "EUROP", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "EUROP", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0x8835a2f66a7aaccb297cb985831a616b75e2e16c"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0046", AssetID: "asset-0028", Name: "EUROP", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "EUROP", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("euro5sNHrZC2wu2RoLvy6xxoVMc3Qnd1vjxoWf4MftA"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0047", AssetID: "asset-0029", Name: "GYEN", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "GYEN", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc08512927d12348f6620a698105e1baac6ecd911"), Status: TokenStatus("winding-down"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0048", AssetID: "asset-0029", Name: "GYEN", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("JPY"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "GYEN", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("Crn4x1Y2HUKko7ox2EZMT6N2t2ZyH7eKtwkBGVnhEq1g"), Status: TokenStatus("winding-down"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0049", AssetID: "asset-0030", Name: "ZUSD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "ZUSD", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc56c2b7e71b54d38aab6d52e94a04cbfa8f604fa"), Status: TokenStatus("winding-down"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0050", AssetID: "asset-0030", Name: "ZUSD", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("USD"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "ZUSD", Decimals: 6, Standard: TokenStandard("spl-token-2022"),
			Address: tokenString("FrBfWJ4qE5sCzKm3k3JaAtqZcXUh4LvJygDeketsrsH4"), Status: TokenStatus("winding-down"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0051", AssetID: "asset-0031", Name: "Angle EURA", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURA", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x1a7e4e63778b4f12a199c062f3efdd288afcbce8"), Status: TokenStatus("winding-down"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0052", AssetID: "asset-0032", Name: "STASIS EURS", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURS", Decimals: 2, Standard: TokenStandard("erc20"),
			Address: tokenString("0xdb25f211ab05b1c97d595516f45794528a807ad8"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0053", AssetID: "asset-0033", Name: "Monerium EURe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURe", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x3231cb76718cdef2155fc47b5286d82e6eda273f"), Status: TokenStatus("legacy"), ReplacedByDeploymentID: tokenString("deployment-0054"),
		},
		{
			DeploymentID: "deployment-0054", AssetID: "asset-0033", Name: "Monerium EURe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: tokenString("EUR"), UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "EURe", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x39b8b6385416f4ca36a20319f70d28621895279d"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0055", AssetID: "asset-0034", Name: "Uniswap", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "UNI", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0056", AssetID: "asset-0035", Name: "Aave", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "AAVE", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0057", AssetID: "asset-0036", Name: "Chainlink", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "LINK", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x514910771af9ca656af840dff83e8264ecf986ca"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0058", AssetID: "asset-0037", Name: "Bridged Chainlink", RepresentationKind: TokenRepresentationKind("bridged"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: tokenString("asset-0036"),
			ChainID: TokenChainID("eip155:43114"), Symbol: "LINK", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x5947bb275c521040051d82396192181b413227a3"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0059", AssetID: "asset-0038", Name: "Trader Joe", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "JOE", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x6e84a6216ea6dacc71ee8e6b0a5b7322eebc0fdd"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "deployment-0060", AssetID: "asset-0039", Name: "Jupiter", RepresentationKind: TokenRepresentationKind("issued"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"), Symbol: "JUP", Decimals: 6, Standard: TokenStandard("spl-token"),
			Address: tokenString("JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5", AssetID: "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5", Name: "Unclassified token at 0x0f5d2fb29fb7d3cfee444a200298f468908cc942", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x0f5d2fb29fb7d3cfee444a200298f468908cc942", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x0f5d2fb29fb7d3cfee444a200298f468908cc942"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692", AssetID: "discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692", Name: "Unclassified token at 0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804", AssetID: "discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804", Name: "Unclassified token at 0x02e955e93055e5a9d7fe6e9ee65126b321acef76", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x02e955e93055e5a9d7fe6e9ee65126b321acef76", Decimals: 9, Standard: TokenStandard("erc20"),
			Address: tokenString("0x02e955e93055e5a9d7fe6e9ee65126b321acef76"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5", AssetID: "discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5", Name: "Unclassified token at 0xc7198437980c041c805a1edcba50c1ce5db95118", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0xc7198437980c041c805a1edcba50c1ce5db95118", Decimals: 6, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc7198437980c041c805a1edcba50c1ce5db95118"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-2ad4730de37ecbe3f9219de3eaf0c5d66062ad8a4a7141f75f44122844f55305", AssetID: "discovered-token-2ad4730de37ecbe3f9219de3eaf0c5d66062ad8a4a7141f75f44122844f55305", Name: "Unclassified token at 0x8729438eb15e2c8b576fcc6aecda6a148776c0f5", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x8729438eb15e2c8b576fcc6aecda6a148776c0f5", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x8729438eb15e2c8b576fcc6aecda6a148776c0f5"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d", AssetID: "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d", Name: "Unclassified token at 0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371", AssetID: "discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371", Name: "Unclassified token at 0x3ceeb67533e494c0dc6be579585e3c62916062e0", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x3ceeb67533e494c0dc6be579585e3c62916062e0", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x3ceeb67533e494c0dc6be579585e3c62916062e0"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-5d9e514643710480cadd0be3aedb94f01fe8cd7b5d4d1ea4556392a3a9177512", AssetID: "discovered-token-5d9e514643710480cadd0be3aedb94f01fe8cd7b5d4d1ea4556392a3a9177512", Name: "Unclassified token at 0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xd1c3f94de7e5b45fa4edbba472491a9f4b166fc4"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec", AssetID: "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec", Name: "Unclassified token at 0x2b591e99afe9f32eaa6214f7b7629768c40eeb39", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x2b591e99afe9f32eaa6214f7b7629768c40eeb39", Decimals: 8, Standard: TokenStandard("erc20"),
			Address: tokenString("0x2b591e99afe9f32eaa6214f7b7629768c40eeb39"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6", AssetID: "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6", Name: "Unclassified token at 0x0d8775f648430679a709e98d2b0cb6250d2887ef", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x0d8775f648430679a709e98d2b0cb6250d2887ef", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x0d8775f648430679a709e98d2b0cb6250d2887ef"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-7028d97cbfa0ea3ea143c41320a542a002a7c21be7a0f6e38ca8c2053789917c", AssetID: "discovered-token-7028d97cbfa0ea3ea143c41320a542a002a7c21be7a0f6e38ca8c2053789917c", Name: "Unclassified token at 0xd586e7f844cea2f87f50152665bcbc2c279d8d70", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0xd586e7f844cea2f87f50152665bcbc2c279d8d70", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0xd586e7f844cea2f87f50152665bcbc2c279d8d70"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-991aaccb7a9c45364e52c40b90f6e1cc12c38d4270f8e936f7258c8a450f2bf2", AssetID: "discovered-token-991aaccb7a9c45364e52c40b90f6e1cc12c38d4270f8e936f7258c8a450f2bf2", Name: "Unclassified token at 0x82fe038ea4b50f9c957da326c412ebd73462077c", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x82fe038ea4b50f9c957da326c412ebd73462077c", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x82fe038ea4b50f9c957da326c412ebd73462077c"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d", AssetID: "discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d", Name: "Unclassified token at 0x50b7545627a5162f82a992c33b87adc75187b218", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:43114"), Symbol: "0x50b7545627a5162f82a992c33b87adc75187b218", Decimals: 8, Standard: TokenStandard("erc20"),
			Address: tokenString("0x50b7545627a5162f82a992c33b87adc75187b218"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6", AssetID: "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6", Name: "Unclassified token at 0xd46ba6d942050d489dbd938a2c909a5d5039a161", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0xd46ba6d942050d489dbd938a2c909a5d5039a161", Decimals: 9, Standard: TokenStandard("erc20"),
			Address: tokenString("0xd46ba6d942050d489dbd938a2c909a5d5039a161"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395", AssetID: "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395", Name: "Unclassified token at 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556", AssetID: "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556", Name: "Unclassified token at 0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0", Decimals: 18, Standard: TokenStandard("erc20"),
			Address: tokenString("0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
		{
			DeploymentID: "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07", AssetID: "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07", Name: "Unclassified token at 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599", RepresentationKind: TokenRepresentationKind("unclassified"),
			StableCurrency: nil, UnderlyingAssetID: nil, EconomicReferenceAssetID: nil,
			ChainID: TokenChainID("eip155:1"), Symbol: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599", Decimals: 8, Standard: TokenStandard("erc20"),
			Address: tokenString("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"), Status: TokenStatus("active"), ReplacedByDeploymentID: nil,
		},
	}
}

func TokenAliases() []TokenAlias {
	return []TokenAlias{
		{Namespace: "avalancheC", Name: "AUSD", DeploymentID: TokenAvalancheCAUSD},
		{Namespace: "avalancheC", Name: "AVAX", DeploymentID: TokenAvalancheCAVAX},
		{Namespace: "avalancheC", Name: "DISCOVERED_0A7F98C8752F15EE", DeploymentID: TokenAvalancheCDISCOVERED_0A7F98C8752F15EE},
		{Namespace: "avalancheC", Name: "DISCOVERED_1847342426B765AD", DeploymentID: TokenAvalancheCDISCOVERED_1847342426B765AD},
		{Namespace: "avalancheC", Name: "DISCOVERED_288036A90EE0FA72", DeploymentID: TokenAvalancheCDISCOVERED_288036A90EE0FA72},
		{Namespace: "avalancheC", Name: "DISCOVERED_2AD4730DE37ECBE3", DeploymentID: TokenAvalancheCDISCOVERED_2AD4730DE37ECBE3},
		{Namespace: "avalancheC", Name: "DISCOVERED_323D07C442F0D089", DeploymentID: TokenAvalancheCDISCOVERED_323D07C442F0D089},
		{Namespace: "avalancheC", Name: "DISCOVERED_5D9E514643710480", DeploymentID: TokenAvalancheCDISCOVERED_5D9E514643710480},
		{Namespace: "avalancheC", Name: "DISCOVERED_7028D97CBFA0EA3E", DeploymentID: TokenAvalancheCDISCOVERED_7028D97CBFA0EA3E},
		{Namespace: "avalancheC", Name: "DISCOVERED_991AACCB7A9C4536", DeploymentID: TokenAvalancheCDISCOVERED_991AACCB7A9C4536},
		{Namespace: "avalancheC", Name: "DISCOVERED_9F9965CC065C9BEC", DeploymentID: TokenAvalancheCDISCOVERED_9F9965CC065C9BEC},
		{Namespace: "avalancheC", Name: "EURC", DeploymentID: TokenAvalancheCEURC},
		{Namespace: "avalancheC", Name: "EUROP", DeploymentID: TokenAvalancheCEUROP},
		{Namespace: "avalancheC", Name: "GHO", DeploymentID: TokenAvalancheCGHO},
		{Namespace: "avalancheC", Name: "JOE", DeploymentID: TokenAvalancheCJOE},
		{Namespace: "avalancheC", Name: "JPYC", DeploymentID: TokenAvalancheCJPYC},
		{Namespace: "avalancheC", Name: "LINK", DeploymentID: TokenAvalancheCLINK},
		{Namespace: "avalancheC", Name: "USDC", DeploymentID: TokenAvalancheCUSDC},
		{Namespace: "avalancheC", Name: "USDC_E", DeploymentID: TokenAvalancheCUSDC_E},
		{Namespace: "avalancheC", Name: "USDT", DeploymentID: TokenAvalancheCUSDT},
		{Namespace: "avalancheC", Name: "WAVAX", DeploymentID: TokenAvalancheCWAVAX},
		{Namespace: "ethereum", Name: "AAVE", DeploymentID: TokenEthereumAAVE},
		{Namespace: "ethereum", Name: "AUSD", DeploymentID: TokenEthereumAUSD},
		{Namespace: "ethereum", Name: "DAI", DeploymentID: TokenEthereumDAI},
		{Namespace: "ethereum", Name: "DISCOVERED_054D80A64E1F36A7", DeploymentID: TokenEthereumDISCOVERED_054D80A64E1F36A7},
		{Namespace: "ethereum", Name: "DISCOVERED_2FA5450C9FA7285D", DeploymentID: TokenEthereumDISCOVERED_2FA5450C9FA7285D},
		{Namespace: "ethereum", Name: "DISCOVERED_611597BD13DAA43D", DeploymentID: TokenEthereumDISCOVERED_611597BD13DAA43D},
		{Namespace: "ethereum", Name: "DISCOVERED_69519FD08E31445C", DeploymentID: TokenEthereumDISCOVERED_69519FD08E31445C},
		{Namespace: "ethereum", Name: "DISCOVERED_A8375562798BC4AE", DeploymentID: TokenEthereumDISCOVERED_A8375562798BC4AE},
		{Namespace: "ethereum", Name: "DISCOVERED_B475569F6A15E97A", DeploymentID: TokenEthereumDISCOVERED_B475569F6A15E97A},
		{Namespace: "ethereum", Name: "DISCOVERED_E2D57F6E6123C78A", DeploymentID: TokenEthereumDISCOVERED_E2D57F6E6123C78A},
		{Namespace: "ethereum", Name: "DISCOVERED_E375086901067FE3", DeploymentID: TokenEthereumDISCOVERED_E375086901067FE3},
		{Namespace: "ethereum", Name: "ETH", DeploymentID: TokenEthereumETH},
		{Namespace: "ethereum", Name: "EURA", DeploymentID: TokenEthereumEURA},
		{Namespace: "ethereum", Name: "EURAU", DeploymentID: TokenEthereumEURAU},
		{Namespace: "ethereum", Name: "EURC", DeploymentID: TokenEthereumEURC},
		{Namespace: "ethereum", Name: "EURCV", DeploymentID: TokenEthereumEURCV},
		{Namespace: "ethereum", Name: "EURE", DeploymentID: TokenEthereumEURE},
		{Namespace: "ethereum", Name: "EURE_V1", DeploymentID: TokenEthereumEURE_V1},
		{Namespace: "ethereum", Name: "EUROP", DeploymentID: TokenEthereumEUROP},
		{Namespace: "ethereum", Name: "EURS", DeploymentID: TokenEthereumEURS},
		{Namespace: "ethereum", Name: "EURT", DeploymentID: TokenEthereumEURT},
		{Namespace: "ethereum", Name: "FDUSD", DeploymentID: TokenEthereumFDUSD},
		{Namespace: "ethereum", Name: "GHO", DeploymentID: TokenEthereumGHO},
		{Namespace: "ethereum", Name: "GYEN", DeploymentID: TokenEthereumGYEN},
		{Namespace: "ethereum", Name: "JPYC", DeploymentID: TokenEthereumJPYC},
		{Namespace: "ethereum", Name: "LINK", DeploymentID: TokenEthereumLINK},
		{Namespace: "ethereum", Name: "PYUSD", DeploymentID: TokenEthereumPYUSD},
		{Namespace: "ethereum", Name: "RLUSD", DeploymentID: TokenEthereumRLUSD},
		{Namespace: "ethereum", Name: "UNI", DeploymentID: TokenEthereumUNI},
		{Namespace: "ethereum", Name: "USDC", DeploymentID: TokenEthereumUSDC},
		{Namespace: "ethereum", Name: "USDE", DeploymentID: TokenEthereumUSDE},
		{Namespace: "ethereum", Name: "USDG", DeploymentID: TokenEthereumUSDG},
		{Namespace: "ethereum", Name: "USDP", DeploymentID: TokenEthereumUSDP},
		{Namespace: "ethereum", Name: "USDS", DeploymentID: TokenEthereumUSDS},
		{Namespace: "ethereum", Name: "USDT", DeploymentID: TokenEthereumUSDT},
		{Namespace: "ethereum", Name: "WETH", DeploymentID: TokenEthereumWETH},
		{Namespace: "ethereum", Name: "ZUSD", DeploymentID: TokenEthereumZUSD},
		{Namespace: "solana", Name: "AUSD", DeploymentID: TokenSolanaAUSD},
		{Namespace: "solana", Name: "EURAU", DeploymentID: TokenSolanaEURAU},
		{Namespace: "solana", Name: "EURC", DeploymentID: TokenSolanaEURC},
		{Namespace: "solana", Name: "EURCV", DeploymentID: TokenSolanaEURCV},
		{Namespace: "solana", Name: "EUROP", DeploymentID: TokenSolanaEUROP},
		{Namespace: "solana", Name: "FDUSD", DeploymentID: TokenSolanaFDUSD},
		{Namespace: "solana", Name: "GYEN", DeploymentID: TokenSolanaGYEN},
		{Namespace: "solana", Name: "JUP", DeploymentID: TokenSolanaJUP},
		{Namespace: "solana", Name: "JUPUSD", DeploymentID: TokenSolanaJUPUSD},
		{Namespace: "solana", Name: "PYUSD", DeploymentID: TokenSolanaPYUSD},
		{Namespace: "solana", Name: "SOL", DeploymentID: TokenSolanaSOL},
		{Namespace: "solana", Name: "USDC", DeploymentID: TokenSolanaUSDC},
		{Namespace: "solana", Name: "USDG", DeploymentID: TokenSolanaUSDG},
		{Namespace: "solana", Name: "USDP", DeploymentID: TokenSolanaUSDP},
		{Namespace: "solana", Name: "USDS", DeploymentID: TokenSolanaUSDS},
		{Namespace: "solana", Name: "USDT", DeploymentID: TokenSolanaUSDT},
		{Namespace: "solana", Name: "WSOL", DeploymentID: TokenSolanaWSOL},
		{Namespace: "solana", Name: "WSOL_TOKEN_2022", DeploymentID: TokenSolanaWSOL_TOKEN_2022},
		{Namespace: "solana", Name: "ZUSD", DeploymentID: TokenSolanaZUSD},
	}
}

type TokenAvalancheCAliases struct {
	AUSD                        string
	AVAX                        string
	DISCOVERED_0A7F98C8752F15EE string
	DISCOVERED_1847342426B765AD string
	DISCOVERED_288036A90EE0FA72 string
	DISCOVERED_2AD4730DE37ECBE3 string
	DISCOVERED_323D07C442F0D089 string
	DISCOVERED_5D9E514643710480 string
	DISCOVERED_7028D97CBFA0EA3E string
	DISCOVERED_991AACCB7A9C4536 string
	DISCOVERED_9F9965CC065C9BEC string
	EURC                        string
	EUROP                       string
	GHO                         string
	JOE                         string
	JPYC                        string
	LINK                        string
	USDC                        string
	USDC_E                      string
	USDT                        string
	WAVAX                       string
}

type TokenEthereumAliases struct {
	AAVE                        string
	AUSD                        string
	DAI                         string
	DISCOVERED_054D80A64E1F36A7 string
	DISCOVERED_2FA5450C9FA7285D string
	DISCOVERED_611597BD13DAA43D string
	DISCOVERED_69519FD08E31445C string
	DISCOVERED_A8375562798BC4AE string
	DISCOVERED_B475569F6A15E97A string
	DISCOVERED_E2D57F6E6123C78A string
	DISCOVERED_E375086901067FE3 string
	ETH                         string
	EURA                        string
	EURAU                       string
	EURC                        string
	EURCV                       string
	EURE                        string
	EURE_V1                     string
	EUROP                       string
	EURS                        string
	EURT                        string
	FDUSD                       string
	GHO                         string
	GYEN                        string
	JPYC                        string
	LINK                        string
	PYUSD                       string
	RLUSD                       string
	UNI                         string
	USDC                        string
	USDE                        string
	USDG                        string
	USDP                        string
	USDS                        string
	USDT                        string
	WETH                        string
	ZUSD                        string
}

type TokenSolanaAliases struct {
	AUSD            string
	EURAU           string
	EURC            string
	EURCV           string
	EUROP           string
	FDUSD           string
	GYEN            string
	JUP             string
	JUPUSD          string
	PYUSD           string
	SOL             string
	USDC            string
	USDG            string
	USDP            string
	USDS            string
	USDT            string
	WSOL            string
	WSOL_TOKEN_2022 string
	ZUSD            string
}

type TokenAliasGroups struct {
	Ethereum   TokenEthereumAliases
	Solana     TokenSolanaAliases
	AvalancheC TokenAvalancheCAliases
}

func TokenAliasIDs() TokenAliasGroups {
	return TokenAliasGroups{
		Ethereum: TokenEthereumAliases{
			AAVE:                        TokenEthereumAAVE,
			AUSD:                        TokenEthereumAUSD,
			DAI:                         TokenEthereumDAI,
			DISCOVERED_054D80A64E1F36A7: TokenEthereumDISCOVERED_054D80A64E1F36A7,
			DISCOVERED_2FA5450C9FA7285D: TokenEthereumDISCOVERED_2FA5450C9FA7285D,
			DISCOVERED_611597BD13DAA43D: TokenEthereumDISCOVERED_611597BD13DAA43D,
			DISCOVERED_69519FD08E31445C: TokenEthereumDISCOVERED_69519FD08E31445C,
			DISCOVERED_A8375562798BC4AE: TokenEthereumDISCOVERED_A8375562798BC4AE,
			DISCOVERED_B475569F6A15E97A: TokenEthereumDISCOVERED_B475569F6A15E97A,
			DISCOVERED_E2D57F6E6123C78A: TokenEthereumDISCOVERED_E2D57F6E6123C78A,
			DISCOVERED_E375086901067FE3: TokenEthereumDISCOVERED_E375086901067FE3,
			ETH:                         TokenEthereumETH,
			EURA:                        TokenEthereumEURA,
			EURAU:                       TokenEthereumEURAU,
			EURC:                        TokenEthereumEURC,
			EURCV:                       TokenEthereumEURCV,
			EURE:                        TokenEthereumEURE,
			EURE_V1:                     TokenEthereumEURE_V1,
			EUROP:                       TokenEthereumEUROP,
			EURS:                        TokenEthereumEURS,
			EURT:                        TokenEthereumEURT,
			FDUSD:                       TokenEthereumFDUSD,
			GHO:                         TokenEthereumGHO,
			GYEN:                        TokenEthereumGYEN,
			JPYC:                        TokenEthereumJPYC,
			LINK:                        TokenEthereumLINK,
			PYUSD:                       TokenEthereumPYUSD,
			RLUSD:                       TokenEthereumRLUSD,
			UNI:                         TokenEthereumUNI,
			USDC:                        TokenEthereumUSDC,
			USDE:                        TokenEthereumUSDE,
			USDG:                        TokenEthereumUSDG,
			USDP:                        TokenEthereumUSDP,
			USDS:                        TokenEthereumUSDS,
			USDT:                        TokenEthereumUSDT,
			WETH:                        TokenEthereumWETH,
			ZUSD:                        TokenEthereumZUSD,
		},
		Solana: TokenSolanaAliases{
			AUSD:            TokenSolanaAUSD,
			EURAU:           TokenSolanaEURAU,
			EURC:            TokenSolanaEURC,
			EURCV:           TokenSolanaEURCV,
			EUROP:           TokenSolanaEUROP,
			FDUSD:           TokenSolanaFDUSD,
			GYEN:            TokenSolanaGYEN,
			JUP:             TokenSolanaJUP,
			JUPUSD:          TokenSolanaJUPUSD,
			PYUSD:           TokenSolanaPYUSD,
			SOL:             TokenSolanaSOL,
			USDC:            TokenSolanaUSDC,
			USDG:            TokenSolanaUSDG,
			USDP:            TokenSolanaUSDP,
			USDS:            TokenSolanaUSDS,
			USDT:            TokenSolanaUSDT,
			WSOL:            TokenSolanaWSOL,
			WSOL_TOKEN_2022: TokenSolanaWSOL_TOKEN_2022,
			ZUSD:            TokenSolanaZUSD,
		},
		AvalancheC: TokenAvalancheCAliases{
			AUSD:                        TokenAvalancheCAUSD,
			AVAX:                        TokenAvalancheCAVAX,
			DISCOVERED_0A7F98C8752F15EE: TokenAvalancheCDISCOVERED_0A7F98C8752F15EE,
			DISCOVERED_1847342426B765AD: TokenAvalancheCDISCOVERED_1847342426B765AD,
			DISCOVERED_288036A90EE0FA72: TokenAvalancheCDISCOVERED_288036A90EE0FA72,
			DISCOVERED_2AD4730DE37ECBE3: TokenAvalancheCDISCOVERED_2AD4730DE37ECBE3,
			DISCOVERED_323D07C442F0D089: TokenAvalancheCDISCOVERED_323D07C442F0D089,
			DISCOVERED_5D9E514643710480: TokenAvalancheCDISCOVERED_5D9E514643710480,
			DISCOVERED_7028D97CBFA0EA3E: TokenAvalancheCDISCOVERED_7028D97CBFA0EA3E,
			DISCOVERED_991AACCB7A9C4536: TokenAvalancheCDISCOVERED_991AACCB7A9C4536,
			DISCOVERED_9F9965CC065C9BEC: TokenAvalancheCDISCOVERED_9F9965CC065C9BEC,
			EURC:                        TokenAvalancheCEURC,
			EUROP:                       TokenAvalancheCEUROP,
			GHO:                         TokenAvalancheCGHO,
			JOE:                         TokenAvalancheCJOE,
			JPYC:                        TokenAvalancheCJPYC,
			LINK:                        TokenAvalancheCLINK,
			USDC:                        TokenAvalancheCUSDC,
			USDC_E:                      TokenAvalancheCUSDC_E,
			USDT:                        TokenAvalancheCUSDT,
			WAVAX:                       TokenAvalancheCWAVAX,
		},
	}
}

const TokenAvalancheCAUSD = "deployment-0035"
const TokenAvalancheCAVAX = "deployment-0003"
const TokenAvalancheCDISCOVERED_0A7F98C8752F15EE = "discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692"
const TokenAvalancheCDISCOVERED_1847342426B765AD = "discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804"
const TokenAvalancheCDISCOVERED_288036A90EE0FA72 = "discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5"
const TokenAvalancheCDISCOVERED_2AD4730DE37ECBE3 = "discovered-token-2ad4730de37ecbe3f9219de3eaf0c5d66062ad8a4a7141f75f44122844f55305"
const TokenAvalancheCDISCOVERED_323D07C442F0D089 = "discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371"
const TokenAvalancheCDISCOVERED_5D9E514643710480 = "discovered-token-5d9e514643710480cadd0be3aedb94f01fe8cd7b5d4d1ea4556392a3a9177512"
const TokenAvalancheCDISCOVERED_7028D97CBFA0EA3E = "discovered-token-7028d97cbfa0ea3ea143c41320a542a002a7c21be7a0f6e38ca8c2053789917c"
const TokenAvalancheCDISCOVERED_991AACCB7A9C4536 = "discovered-token-991aaccb7a9c45364e52c40b90f6e1cc12c38d4270f8e936f7258c8a450f2bf2"
const TokenAvalancheCDISCOVERED_9F9965CC065C9BEC = "discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d"
const TokenAvalancheCEURC = "deployment-0012"
const TokenAvalancheCEUROP = "deployment-0045"
const TokenAvalancheCGHO = "deployment-0030"
const TokenAvalancheCJOE = "deployment-0059"
const TokenAvalancheCJPYC = "deployment-0039"
const TokenAvalancheCLINK = "deployment-0058"
const TokenAvalancheCUSDC = "deployment-0009"
const TokenAvalancheCUSDC_E = "deployment-0018"
const TokenAvalancheCUSDT = "deployment-0015"
const TokenAvalancheCWAVAX = "deployment-0004"
const TokenEthereumAAVE = "deployment-0056"
const TokenEthereumAUSD = "deployment-0034"
const TokenEthereumDAI = "deployment-0019"
const TokenEthereumDISCOVERED_054D80A64E1F36A7 = "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5"
const TokenEthereumDISCOVERED_2FA5450C9FA7285D = "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d"
const TokenEthereumDISCOVERED_611597BD13DAA43D = "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec"
const TokenEthereumDISCOVERED_69519FD08E31445C = "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6"
const TokenEthereumDISCOVERED_A8375562798BC4AE = "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6"
const TokenEthereumDISCOVERED_B475569F6A15E97A = "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395"
const TokenEthereumDISCOVERED_E2D57F6E6123C78A = "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556"
const TokenEthereumDISCOVERED_E375086901067FE3 = "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07"
const TokenEthereumETH = "deployment-0001"
const TokenEthereumEURA = "deployment-0051"
const TokenEthereumEURAU = "deployment-0042"
const TokenEthereumEURC = "deployment-0011"
const TokenEthereumEURCV = "deployment-0040"
const TokenEthereumEURE = "deployment-0054"
const TokenEthereumEURE_V1 = "deployment-0053"
const TokenEthereumEUROP = "deployment-0044"
const TokenEthereumEURS = "deployment-0052"
const TokenEthereumEURT = "deployment-0017"
const TokenEthereumFDUSD = "deployment-0031"
const TokenEthereumGHO = "deployment-0029"
const TokenEthereumGYEN = "deployment-0047"
const TokenEthereumJPYC = "deployment-0038"
const TokenEthereumLINK = "deployment-0057"
const TokenEthereumPYUSD = "deployment-0022"
const TokenEthereumRLUSD = "deployment-0033"
const TokenEthereumUNI = "deployment-0055"
const TokenEthereumUSDC = "deployment-0008"
const TokenEthereumUSDE = "deployment-0028"
const TokenEthereumUSDG = "deployment-0024"
const TokenEthereumUSDP = "deployment-0026"
const TokenEthereumUSDS = "deployment-0020"
const TokenEthereumUSDT = "deployment-0014"
const TokenEthereumWETH = "deployment-0002"
const TokenEthereumZUSD = "deployment-0049"
const TokenSolanaAUSD = "deployment-0036"
const TokenSolanaEURAU = "deployment-0043"
const TokenSolanaEURC = "deployment-0013"
const TokenSolanaEURCV = "deployment-0041"
const TokenSolanaEUROP = "deployment-0046"
const TokenSolanaFDUSD = "deployment-0032"
const TokenSolanaGYEN = "deployment-0048"
const TokenSolanaJUP = "deployment-0060"
const TokenSolanaJUPUSD = "deployment-0037"
const TokenSolanaPYUSD = "deployment-0023"
const TokenSolanaSOL = "deployment-0005"
const TokenSolanaUSDC = "deployment-0010"
const TokenSolanaUSDG = "deployment-0025"
const TokenSolanaUSDP = "deployment-0027"
const TokenSolanaUSDS = "deployment-0021"
const TokenSolanaUSDT = "deployment-0016"
const TokenSolanaWSOL = "deployment-0006"
const TokenSolanaWSOL_TOKEN_2022 = "deployment-0007"
const TokenSolanaZUSD = "deployment-0050"
