// Generated by registry/generate-token-rankings.mjs. Do not edit.
package erpc

func tokenRankingString(value string) *string { return &value }

type TokenRanking struct {
	Rank              int
	ChainID           string
	DeploymentIDs     []string
	Metric            string
	ValueNumerator    string
	ValueDenominator  string
	QuoteCurrency     string
	QuoteDeploymentID *string
	ObservedAt        string
	SourceID          string
	SourceAssetID     *string
}
type TokenRankingCoverage struct {
	ChainID             string
	TotalDeployments    int
	RankedDeployments   int
	UnrankedDeployments int
	ObservedAt          *string
}
type TokenRankingSnapshotMetadata struct {
	SchemaVersion int
	Metric        *string
	AsOf          *string
	ContentDigest string
	Status        string
	Coverage      []TokenRankingCoverage
	SourceIDs     []string
}

const TokenRankingsSchemaVersion = 1
const TokenRankingsMetric = "onchain-total-supply-value-native"
const TokenRankingsAsOf = "2026-09-19T07:50:47Z"
const TokenRankingsContentDigest = "bd716a04d7c03e55014ba01317909031f7dbe68f8b2c65140bb7759fbbd67cc4"
const TokenRankingsStatus = "partial"

var tokenRankingsMetricValue = tokenRankingString("onchain-total-supply-value-native")
var tokenRankingsAsOfValue = tokenRankingString("2026-09-19T07:50:47Z")
var tokenRankingsCoverage = []TokenRankingCoverage{{ChainID: "eip155:1", TotalDeployments: 37, RankedDeployments: 12, UnrankedDeployments: 25, ObservedAt: tokenRankingString("2026-09-19T07:50:47Z")}, {ChainID: "eip155:43114", TotalDeployments: 21, RankedDeployments: 12, UnrankedDeployments: 9, ObservedAt: tokenRankingString("2026-09-19T08:08:22Z")}, {ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", TotalDeployments: 19, RankedDeployments: 1, UnrankedDeployments: 18, ObservedAt: tokenRankingString("2026-09-19T08:08:14Z")}}
var tokenRankingsSourceIDs = []string{"rpc-avalanche-c-mainnet", "rpc-ethereum-mainnet", "rpc-solana-mainnet"}
var tokenRankings = []TokenRanking{
	{Rank: 1, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0014"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "125787492690000662815190858411535566592", ValueDenominator: "3743511970879", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 2, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0008"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "197943216237595054112852670973131065113", ValueDenominator: "10378928158470", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 3, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0057"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "34739515818909499644625000000000000000000000000", ValueDenominator: "7390864991655120049419", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 4, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "20010697177818023618868775218767936", ValueDenominator: "5579661419", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 5, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0019"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "8232694377260883052515747886767444213670607928915", ValueDenominator: "4696474932745322150903386", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 6, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "248368570575692041025000000000000000000000000000", ValueDenominator: "630362105596579587002139", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 7, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "16703469569691299414484861075220147077304949440", ValueDenominator: "251595044709968052670663", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 8, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "11641021485646457313679012179791613958020834", ValueDenominator: "221664454521656762539", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 9, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "5887681530380046453265015167097118744825532877", ValueDenominator: "119395039198397560618910", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 10, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "5867693999418683040750000000000000000000000000", ValueDenominator: "129012501081396330225407", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 11, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "195507342537557306196135660433456203136", ValueDenominator: "7096954321157825", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 12, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "51601783187842940267302169603853472", ValueDenominator: "37033188447463", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-19T07:50:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 1, ChainID: "eip155:43114", DeploymentIDs: []string{"deployment-0009"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "1815697633175758647302595823339631397", ValueDenominator: "39876820451", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 2, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-0a7f98c8752f15ee02ce0d801f25df8ff78864a1d70aff7e204f7bdb3f8a0692"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "215110121514852220864491280344848784767622146", ValueDenominator: "48667138452351281703", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 3, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-9f9965cc065c9becf8d2cb58071524baafea37d27fda9bf683a93ea85f2e653d"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "104710146919628009790707765980305", ValueDenominator: "35088757", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 4, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-288036a90ee0fa72a2751a78a6934cc6ced9e16de91c97ae8e109e2ee6189bc5"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "559887456261172382396278287583401488", ValueDenominator: "270742068917", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 5, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-5d9e514643710480cadd0be3aedb94f01fe8cd7b5d4d1ea4556392a3a9177512"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "33366313995183788249150000000000000000000000000", ValueDenominator: "17687105096504008409237", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 6, ChainID: "eip155:43114", DeploymentIDs: []string{"deployment-0059"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "3799391151143569379828795004821953699507932314383", ValueDenominator: "2073975469010023267765866", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 7, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-7028d97cbfa0ea3ea143c41320a542a002a7c21be7a0f6e38ca8c2053789917c"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "21953391176890518902516604872871702108351278097", ValueDenominator: "17582851835084413325432", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 8, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-2ad4730de37ecbe3f9219de3eaf0c5d66062ad8a4a7141f75f44122844f55305"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "14462161652158228991845800000000000000000000000000", ValueDenominator: "12898672520461343041865681", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 9, ChainID: "eip155:43114", DeploymentIDs: []string{"deployment-0058"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "1191339354327040896377456313820075489213314308", ValueDenominator: "2268603776606448916001", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 10, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-323d07c442f0d089197ae7eea9b3ebb829910177c5b780161a7623aaed5e4371"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "251829511438897642783991908782349109073121335", ValueDenominator: "941407095476872197097", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 11, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-991aaccb7a9c45364e52c40b90f6e1cc12c38d4270f8e936f7258c8a450f2bf2"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "40486673598385057808245500000000000000000", ValueDenominator: "16164012414830534303", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 12, ChainID: "eip155:43114", DeploymentIDs: []string{"discovered-token-1847342426b765add3c8b4feb724c6b15121f25097cb7917c967c285ca77e804"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "1980608245332228056350000000000000000", ValueDenominator: "3284592364734729", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0003"), ObservedAt: "2026-09-19T08:08:22Z", SourceID: "rpc-avalanche-c-mainnet", SourceAssetID: nil},
	{Rank: 1, ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", DeploymentIDs: []string{"deployment-0013"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "35736210348070631431481083302744800328060229973442560", ValueDenominator: "33172162349950615559040645845612581161", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0005"), ObservedAt: "2026-09-19T08:08:14Z", SourceID: "rpc-solana-mainnet", SourceAssetID: nil},
}

func cloneTokenRanking(value TokenRanking) TokenRanking {
	value.DeploymentIDs = append([]string(nil), value.DeploymentIDs...)
	if value.QuoteDeploymentID != nil {
		value.QuoteDeploymentID = tokenRankingString(*value.QuoteDeploymentID)
	}
	if value.SourceAssetID != nil {
		value.SourceAssetID = tokenRankingString(*value.SourceAssetID)
	}
	return value
}
func ListTokenRankings(chainID string) []TokenRanking {
	result := make([]TokenRanking, 0)
	for _, value := range tokenRankings {
		if value.ChainID == chainID {
			result = append(result, cloneTokenRanking(value))
		}
	}
	return result
}
func TokenRankingMetadata() TokenRankingSnapshotMetadata {
	coverage := make([]TokenRankingCoverage, len(tokenRankingsCoverage))
	copy(coverage, tokenRankingsCoverage)
	for index := range coverage {
		if coverage[index].ObservedAt != nil {
			coverage[index].ObservedAt = tokenRankingString(*coverage[index].ObservedAt)
		}
	}
	sourceIDs := make([]string, len(tokenRankingsSourceIDs))
	copy(sourceIDs, tokenRankingsSourceIDs)
	var metric *string
	if tokenRankingsMetricValue != nil {
		metric = tokenRankingString(*tokenRankingsMetricValue)
	}
	var asOf *string
	if tokenRankingsAsOfValue != nil {
		asOf = tokenRankingString(*tokenRankingsAsOfValue)
	}
	return TokenRankingSnapshotMetadata{SchemaVersion: 1, Metric: metric, AsOf: asOf, ContentDigest: TokenRankingsContentDigest, Status: TokenRankingsStatus, Coverage: coverage, SourceIDs: sourceIDs}
}
