// Generated by registry/generate-token-rankings.mjs. Do not edit.
package erpc

func tokenRankingString(value string) *string { return &value }

type TokenRanking struct {
	Rank              int
	ChainID           string
	DeploymentIDs     []string
	Metric            string
	ValueNumerator    string
	ValueDenominator  string
	QuoteCurrency     string
	QuoteDeploymentID *string
	ObservedAt        string
	SourceID          string
	SourceAssetID     *string
}
type TokenRankingCoverage struct {
	ChainID             string
	TotalDeployments    int
	RankedDeployments   int
	UnrankedDeployments int
	ObservedAt          *string
}
type TokenRankingSnapshotMetadata struct {
	SchemaVersion int
	Metric        *string
	AsOf          *string
	ContentDigest string
	Status        string
	Coverage      []TokenRankingCoverage
	SourceIDs     []string
}

const TokenRankingsSchemaVersion = 1
const TokenRankingsMetric = "onchain-total-supply-value-native"
const TokenRankingsAsOf = "2026-09-26T08:22:47Z"
const TokenRankingsContentDigest = "421223bcbf3c8b9cc1d80d72a94d2eba5086dce5df54e743571ab41ea8e5ca05"
const TokenRankingsStatus = "partial"

var tokenRankingsMetricValue = tokenRankingString("onchain-total-supply-value-native")
var tokenRankingsAsOfValue = tokenRankingString("2026-09-26T08:22:47Z")
var tokenRankingsCoverage = []TokenRankingCoverage{{ChainID: "eip155:1", TotalDeployments: 40, RankedDeployments: 15, UnrankedDeployments: 25, ObservedAt: tokenRankingString("2026-09-26T08:22:47Z")}, {ChainID: "eip155:43114", TotalDeployments: 17, RankedDeployments: 0, UnrankedDeployments: 17, ObservedAt: tokenRankingString("2026-09-26T08:41:42Z")}, {ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", TotalDeployments: 19, RankedDeployments: 1, UnrankedDeployments: 18, ObservedAt: tokenRankingString("2026-09-26T08:41:39Z")}}
var tokenRankingsSourceIDs = []string{"rpc-avalanche-c-mainnet", "rpc-ethereum-mainnet", "rpc-solana-mainnet"}
var tokenRankings = []TokenRanking{
	{Rank: 1, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0014"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "248160293823773145040355119214842029360", ValueDenominator: "7558283129113", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 2, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0008"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "196031457519886283824821158833057243842", ValueDenominator: "10484592311777", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 3, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0057"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "295581337731067737617000000000000000000000000000", ValueDenominator: "56560794830534541734179", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 4, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "957140565084151031887711711099192", ValueDenominator: "264340323", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 5, ChainID: "eip155:1", DeploymentIDs: []string{"deployment-0019"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "2701641764716348907454775532403696257017711383693", ValueDenominator: "1582539366001196243003783", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 6, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "7029075597208628428000000000000000000000000000", ValueDenominator: "15926729536933326837269", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 7, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "67825554428867567785456167665748398918507728", ValueDenominator: "905788223463157893461", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 8, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "24229684446286992169845198423108683181733265", ValueDenominator: "425401757533284952103", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 9, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "6302193594474818040077675466985588318598897513", ValueDenominator: "112253321514988050100188", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 10, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "3156968292846552119625000000000000000000000000", ValueDenominator: "60202904234141683996909", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 11, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "113507123765391171272298866334829867331", ValueDenominator: "4461699869491147", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 12, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-de17c35bf41345a60acbabfcc00e8108b2c058299fcb70416e9e15749f22220e"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "340298759466192388937820688321453592", ValueDenominator: "67058588557097", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 13, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-4712886cee128f138bba49725f5df0c310125ac43949b14c0edafcd90ff0d545"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "3068778127001892970000000000000000", ValueDenominator: "1191501313309", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 14, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "324908470728477888198619087623616250", ValueDenominator: "239806935102033", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 15, ChainID: "eip155:1", DeploymentIDs: []string{"discovered-token-23a03dcf2efbe86795f325e3f649738ef7315dfd1f6039c347c515c9c9c612bd"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "5047140397281670054777421770527599908652519875", ValueDenominator: "46213987057290963651257313", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0001"), ObservedAt: "2026-09-26T08:22:47Z", SourceID: "rpc-ethereum-mainnet", SourceAssetID: nil},
	{Rank: 1, ChainID: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp", DeploymentIDs: []string{"deployment-0013"}, Metric: "onchain-total-supply-value-native", ValueNumerator: "2233511678518434604004695204734121451074277789925376", ValueDenominator: "2249639816507038516871179905609837169", QuoteCurrency: "native", QuoteDeploymentID: tokenRankingString("deployment-0005"), ObservedAt: "2026-09-26T08:41:39Z", SourceID: "rpc-solana-mainnet", SourceAssetID: nil},
}

func cloneTokenRanking(value TokenRanking) TokenRanking {
	value.DeploymentIDs = append([]string(nil), value.DeploymentIDs...)
	if value.QuoteDeploymentID != nil {
		value.QuoteDeploymentID = tokenRankingString(*value.QuoteDeploymentID)
	}
	if value.SourceAssetID != nil {
		value.SourceAssetID = tokenRankingString(*value.SourceAssetID)
	}
	return value
}
func ListTokenRankings(chainID string) []TokenRanking {
	result := make([]TokenRanking, 0)
	for _, value := range tokenRankings {
		if value.ChainID == chainID {
			result = append(result, cloneTokenRanking(value))
		}
	}
	return result
}
func TokenRankingMetadata() TokenRankingSnapshotMetadata {
	coverage := make([]TokenRankingCoverage, len(tokenRankingsCoverage))
	copy(coverage, tokenRankingsCoverage)
	for index := range coverage {
		if coverage[index].ObservedAt != nil {
			coverage[index].ObservedAt = tokenRankingString(*coverage[index].ObservedAt)
		}
	}
	sourceIDs := make([]string, len(tokenRankingsSourceIDs))
	copy(sourceIDs, tokenRankingsSourceIDs)
	var metric *string
	if tokenRankingsMetricValue != nil {
		metric = tokenRankingString(*tokenRankingsMetricValue)
	}
	var asOf *string
	if tokenRankingsAsOfValue != nil {
		asOf = tokenRankingString(*tokenRankingsAsOfValue)
	}
	return TokenRankingSnapshotMetadata{SchemaVersion: 1, Metric: metric, AsOf: asOf, ContentDigest: TokenRankingsContentDigest, Status: TokenRankingsStatus, Coverage: coverage, SourceIDs: sourceIDs}
}
