# Generated by registry/generate-dex-catalog.mjs. Do not edit.
from __future__ import annotations

from types import MappingProxyType
from typing import NamedTuple


class DexDeployment(NamedTuple):
    dex_deployment_id: str
    protocol_id: str
    name: str
    chain_id: str
    program_address: str
    adapter_kind: str
    status: str
    replaced_by_dex_deployment_id: str | None

class PoolAdapter(NamedTuple):
    kind: str
    fee_numerator: str | None
    fee_denominator: str | None

class PoolDefinition(NamedTuple):
    pool_definition_id: str
    dex_deployment_id: str
    chain_id: str
    address: str
    token0_deployment_id: str
    token1_deployment_id: str
    adapter: PoolAdapter
    status: str
    replaced_by_pool_definition_id: str | None

class NativeWrapDefinition(NamedTuple):
    native_wrap_definition_id: str
    chain_id: str
    native_token_deployment_id: str
    wrapped_token_deployment_id: str
    status: str

class DexAlias(NamedTuple):
    namespace: str
    name: str
    dex_deployment_id: str | None
    pool_definition_id: str | None

DEX_CATALOG_VERSION = "1.0.0"
DEX_CATALOG_AS_OF_DATE = "2026-09-15"
DEX_CATALOG_CONTENT_DIGEST = "002c05c3c2d5d3917f73a5c2e7b55af9ceb9a682fb49ae28d2421046ee2faa50"
DEX_CHAIN_IDS = MappingProxyType({
    "ethereum": "eip155:1",
    "solana": "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
    "avalancheC": "eip155:43114",
})
DEX_DEPLOYMENTS = (
    DexDeployment(
        dex_deployment_id="dex-deployment-0001",
        protocol_id="uniswap-v2",
        name="Uniswap V2",
        chain_id="eip155:1",
        program_address="0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f",
        adapter_kind="evm-constant-product-v2",
        status="active",
        replaced_by_dex_deployment_id=None,
    ),
    DexDeployment(
        dex_deployment_id="dex-deployment-0002",
        protocol_id="lfj-legacy-constant-product",
        name="LFJ legacy constant-product (Joe V1)",
        chain_id="eip155:43114",
        program_address="0x9ad6c38be94206ca50bb0d90783181662f0cfa10",
        adapter_kind="evm-constant-product-v2",
        status="active",
        replaced_by_dex_deployment_id=None,
    ),
    DexDeployment(
        dex_deployment_id="dex-deployment-0003",
        protocol_id="orca-whirlpools",
        name="Orca Whirlpools",
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        program_address="whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc",
        adapter_kind="solana-orca-whirlpool",
        status="active",
        replaced_by_dex_deployment_id=None,
    ),
    DexDeployment(
        dex_deployment_id="dex-deployment-0004",
        protocol_id="raydium-clmm",
        name="Raydium CLMM",
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        program_address="CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK",
        adapter_kind="solana-raydium-clmm",
        status="active",
        replaced_by_dex_deployment_id=None,
    ),
)
POOL_DEFINITIONS = (
    PoolDefinition(
        pool_definition_id="pool-0001",
        dex_deployment_id="dex-deployment-0001",
        chain_id="eip155:1",
        address="0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc",
        token0_deployment_id="deployment-0008",
        token1_deployment_id="deployment-0002",
        adapter=PoolAdapter(
            kind="evm-constant-product-v2",
            fee_numerator="3",
            fee_denominator="1000",
        ),
        status="active",
        replaced_by_pool_definition_id=None,
    ),
    PoolDefinition(
        pool_definition_id="pool-0002",
        dex_deployment_id="dex-deployment-0002",
        chain_id="eip155:43114",
        address="0xf4003f4efbe8691b60249e6afbd307abe7758adb",
        token0_deployment_id="deployment-0004",
        token1_deployment_id="deployment-0009",
        adapter=PoolAdapter(
            kind="evm-constant-product-v2",
            fee_numerator="3",
            fee_denominator="1000",
        ),
        status="active",
        replaced_by_pool_definition_id=None,
    ),
    PoolDefinition(
        pool_definition_id="pool-0003",
        dex_deployment_id="dex-deployment-0003",
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        address="FgH1dEvyRQoAqJjbUzzKVoM1HYdxTqPwjEF82kDH1kVe",
        token0_deployment_id="deployment-0006",
        token1_deployment_id="deployment-0013",
        adapter=PoolAdapter(
            kind="solana-orca-whirlpool",
            fee_numerator=None,
            fee_denominator=None,
        ),
        status="active",
        replaced_by_pool_definition_id=None,
    ),
    PoolDefinition(
        pool_definition_id="pool-0004",
        dex_deployment_id="dex-deployment-0004",
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        address="AwaVyGAF3N6K4YRUJk55Ui1GquKhKdD6vTCmVvCzXpKf",
        token0_deployment_id="deployment-0006",
        token1_deployment_id="deployment-0013",
        adapter=PoolAdapter(
            kind="solana-raydium-clmm",
            fee_numerator=None,
            fee_denominator=None,
        ),
        status="active",
        replaced_by_pool_definition_id=None,
    ),
)
NATIVE_WRAP_DEFINITIONS = (
    NativeWrapDefinition(
        native_wrap_definition_id="native-wrap-0001",
        chain_id="eip155:1",
        native_token_deployment_id="deployment-0001",
        wrapped_token_deployment_id="deployment-0002",
        status="active",
    ),
    NativeWrapDefinition(
        native_wrap_definition_id="native-wrap-0002",
        chain_id="eip155:43114",
        native_token_deployment_id="deployment-0003",
        wrapped_token_deployment_id="deployment-0004",
        status="active",
    ),
    NativeWrapDefinition(
        native_wrap_definition_id="native-wrap-0003",
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        native_token_deployment_id="deployment-0005",
        wrapped_token_deployment_id="deployment-0006",
        status="active",
    ),
)
DEX_ALIASES = (
    DexAlias(
        namespace="avalancheC",
        name="LFJ_LEGACY",
        dex_deployment_id="dex-deployment-0002",
        pool_definition_id=None,
    ),
    DexAlias(
        namespace="avalancheC",
        name="LFJ_LEGACY_WAVAX_USDC",
        dex_deployment_id=None,
        pool_definition_id="pool-0002",
    ),
    DexAlias(
        namespace="ethereum",
        name="UNISWAP_V2",
        dex_deployment_id="dex-deployment-0001",
        pool_definition_id=None,
    ),
    DexAlias(
        namespace="ethereum",
        name="UNISWAP_V2_USDC_WETH",
        dex_deployment_id=None,
        pool_definition_id="pool-0001",
    ),
    DexAlias(
        namespace="solana",
        name="ORCA_WHIRLPOOLS",
        dex_deployment_id="dex-deployment-0003",
        pool_definition_id=None,
    ),
    DexAlias(
        namespace="solana",
        name="ORCA_WHIRLPOOLS_WSOL_EURC",
        dex_deployment_id=None,
        pool_definition_id="pool-0003",
    ),
    DexAlias(
        namespace="solana",
        name="RAYDIUM_CLMM",
        dex_deployment_id="dex-deployment-0004",
        pool_definition_id=None,
    ),
    DexAlias(
        namespace="solana",
        name="RAYDIUM_CLMM_WSOL_EURC",
        dex_deployment_id=None,
        pool_definition_id="pool-0004",
    ),
)
class _EthereumDexes(NamedTuple):
    UNISWAP_V2: str

class _SolanaDexes(NamedTuple):
    ORCA_WHIRLPOOLS: str
    RAYDIUM_CLMM: str

class _AvalancheCDexes(NamedTuple):
    LFJ_LEGACY: str

class _Dexes(NamedTuple):
    ethereum: _EthereumDexes
    solana: _SolanaDexes
    avalanche_c: _AvalancheCDexes

dexes = _Dexes(
    ethereum=_EthereumDexes(
        UNISWAP_V2="dex-deployment-0001",
    ),
    solana=_SolanaDexes(
        ORCA_WHIRLPOOLS="dex-deployment-0003",
        RAYDIUM_CLMM="dex-deployment-0004",
    ),
    avalanche_c=_AvalancheCDexes(
        LFJ_LEGACY="dex-deployment-0002",
    ),
)
DEXES = dexes

class _EthereumPools(NamedTuple):
    UNISWAP_V2_USDC_WETH: str

class _SolanaPools(NamedTuple):
    ORCA_WHIRLPOOLS_WSOL_EURC: str
    RAYDIUM_CLMM_WSOL_EURC: str

class _AvalancheCPools(NamedTuple):
    LFJ_LEGACY_WAVAX_USDC: str

class _Pools(NamedTuple):
    ethereum: _EthereumPools
    solana: _SolanaPools
    avalanche_c: _AvalancheCPools

pools = _Pools(
    ethereum=_EthereumPools(
        UNISWAP_V2_USDC_WETH="pool-0001",
    ),
    solana=_SolanaPools(
        ORCA_WHIRLPOOLS_WSOL_EURC="pool-0003",
        RAYDIUM_CLMM_WSOL_EURC="pool-0004",
    ),
    avalanche_c=_AvalancheCPools(
        LFJ_LEGACY_WAVAX_USDC="pool-0002",
    ),
)
POOLS = pools

