# Generated by registry/generate-token-rankings.mjs. Do not edit.
from __future__ import annotations

from typing import NamedTuple


class TokenRankingMetadata(NamedTuple):
    schema_version: int
    metric: str | None
    as_of: str | None
    content_digest: str
    status: str
    coverage: tuple[TokenRankingCoverage, ...]
    source_ids: tuple[str, ...]


class TokenRankingCoverage(NamedTuple):
    chain_id: str
    total_deployments: int
    ranked_deployments: int
    unranked_deployments: int
    observed_at: str | None


class TokenRanking(NamedTuple):
    rank: int
    chain_id: str
    deployment_ids: tuple[str, ...]
    metric: str
    value_numerator: str
    value_denominator: str
    quote_currency: str
    quote_deployment_id: str | None
    observed_at: str
    source_id: str
    source_asset_id: str | None


TOKEN_RANKINGS_METADATA = TokenRankingMetadata(
    schema_version=1,
    metric="onchain-total-supply-value-native",
    as_of="2026-10-10T09:39:35Z",
    content_digest="bda3b5ac9425d60cbe4812456f90828b13aa5148e3f061cc431739a3c5283fce",
    status="partial",
    coverage=(
        TokenRankingCoverage(
            chain_id="eip155:1",
            total_deployments=40,
            ranked_deployments=15,
            unranked_deployments=25,
            observed_at="2026-10-10T09:39:35Z",
        ),
        TokenRankingCoverage(
            chain_id="eip155:43114",
            total_deployments=17,
            ranked_deployments=0,
            unranked_deployments=17,
            observed_at="2026-10-10T09:58:01Z",
        ),
        TokenRankingCoverage(
            chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
            total_deployments=19,
            ranked_deployments=1,
            unranked_deployments=18,
            observed_at="2026-10-10T09:57:55Z",
        ),
    ),
    source_ids=tuple(["rpc-avalanche-c-mainnet", "rpc-ethereum-mainnet", "rpc-solana-mainnet"]),
)
TOKEN_RANKINGS = (
    TokenRanking(
        rank=1,
        chain_id="eip155:1",
        deployment_ids=("deployment-0014",),
        metric="onchain-total-supply-value-native",
        value_numerator="64410568516371167409570406123605699904",
        value_denominator="1821232434391",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=2,
        chain_id="eip155:1",
        deployment_ids=("deployment-0008",),
        metric="onchain-total-supply-value-native",
        value_numerator="10355312888232650666743518671601761436",
        value_denominator="531443088025",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=3,
        chain_id="eip155:1",
        deployment_ids=("deployment-0057",),
        metric="onchain-total-supply-value-native",
        value_numerator="146842649128092584332500000000000000000000000000",
        value_denominator="28248516852546744565903",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=4,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="20708104647525464715076265583477654",
        value_denominator="5376748523",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=5,
        chain_id="eip155:1",
        deployment_ids=("deployment-0019",),
        metric="onchain-total-supply-value-native",
        value_numerator="4185819224055777096195322110706695405839227991051",
        value_denominator="2285483340354184133823654",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=6,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-e2d57f6e6123c78a3215badf6e040643117e7e0ca727788ff1ff4fc1e1c3a556",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="168566106837667858670000000000000000000000000000",
        value_denominator="418626596623665471490721",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=7,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="18966072582919196621301441547327189971599204960",
        value_denominator="225722451728433739387569",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=8,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="45714639084341267835937500000000000000000000",
        value_denominator="549489879777098190107",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=9,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="24732402174716344989897191595354480918028425",
        value_denominator="412714984776950364992",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=10,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-2fa5450c9fa7285d6fc8352d9b7fed6eb042020a7a5e4f72e4181ec21f3e923d",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="6365358574445504321313947745196063250690016067",
        value_denominator="111950314817430776180883",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=11,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="63426125979927716252323276418305507504",
        value_denominator="3118729591730941",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=12,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-de17c35bf41345a60acbabfcc00e8108b2c058299fcb70416e9e15749f22220e",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="678121984646390700074762260229067712",
        value_denominator="136742092124503",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=13,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-4712886cee128f138bba49725f5df0c310125ac43949b14c0edafcd90ff0d545",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="2648614276554353806500000000000000",
        value_denominator="745588861117",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=14,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-a8375562798bc4ae7b3f6f673452be39367f106be864d5ad44d3b5a17ccd04c6",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="34572478164595704875793095918493473",
        value_denominator="26913661850319",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=15,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-23a03dcf2efbe86795f325e3f649738ef7315dfd1f6039c347c515c9c9c612bd",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="416866888863001039935475525590676963921858362",
        value_denominator="4266526329864996995979373",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-10-10T09:39:35Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=1,
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        deployment_ids=("deployment-0013",),
        metric="onchain-total-supply-value-native",
        value_numerator="35736184782161974382238199711998260674716144072916992",
        value_denominator="33312928178967032779363775247166378921",
        quote_currency="native",
        quote_deployment_id="deployment-0005",
        observed_at="2026-10-10T09:57:55Z",
        source_id="rpc-solana-mainnet",
        source_asset_id=None,
    ),
)
TOKEN_RANKINGS_CONTENT_DIGEST = TOKEN_RANKINGS_METADATA.content_digest
