# Generated by registry/generate-token-rankings.mjs. Do not edit.
from __future__ import annotations

from typing import NamedTuple


class TokenRankingMetadata(NamedTuple):
    schema_version: int
    metric: str | None
    as_of: str | None
    content_digest: str
    status: str
    coverage: tuple[TokenRankingCoverage, ...]
    source_ids: tuple[str, ...]


class TokenRankingCoverage(NamedTuple):
    chain_id: str
    total_deployments: int
    ranked_deployments: int
    unranked_deployments: int
    observed_at: str | None


class TokenRanking(NamedTuple):
    rank: int
    chain_id: str
    deployment_ids: tuple[str, ...]
    metric: str
    value_numerator: str
    value_denominator: str
    quote_currency: str
    quote_deployment_id: str | None
    observed_at: str
    source_id: str
    source_asset_id: str | None


TOKEN_RANKINGS_METADATA = TokenRankingMetadata(
    schema_version=1,
    metric="onchain-total-supply-value-native",
    as_of="2026-09-16T16:41:59Z",
    content_digest="26d1dc0a1091c8bfcb475c22877d1ce4ee7384462a184c9d4fc509c57110c0ea",
    status="partial",
    coverage=(
        TokenRankingCoverage(
            chain_id="eip155:1",
            total_deployments=34,
            ranked_deployments=8,
            unranked_deployments=26,
            observed_at="2026-09-16T16:41:59Z",
        ),
        TokenRankingCoverage(
            chain_id="eip155:43114",
            total_deployments=17,
            ranked_deployments=0,
            unranked_deployments=17,
            observed_at="2026-09-16T16:57:22Z",
        ),
        TokenRankingCoverage(
            chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
            total_deployments=19,
            ranked_deployments=1,
            unranked_deployments=18,
            observed_at="2026-09-16T16:57:16Z",
        ),
    ),
    source_ids=tuple(["rpc-avalanche-c-mainnet", "rpc-ethereum-mainnet", "rpc-solana-mainnet"]),
)
TOKEN_RANKINGS = (
    TokenRanking(
        rank=1,
        chain_id="eip155:1",
        deployment_ids=("deployment-0008",),
        metric="onchain-total-supply-value-native",
        value_numerator="207204000029972648356119414046913566875",
        value_denominator="9901974834827",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=2,
        chain_id="eip155:1",
        deployment_ids=("deployment-0057",),
        metric="onchain-total-supply-value-native",
        value_numerator="33884048421157235660750000000000000000000000000",
        value_denominator="7575670698454356114489",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=3,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-e375086901067fe3de023bcdc70f1bafca798e1719ed7e676a98f57de3350a07",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="2530529372917746092314437530549111",
        value_denominator="689351076",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=4,
        chain_id="eip155:1",
        deployment_ids=("deployment-0019",),
        metric="onchain-total-supply-value-native",
        value_numerator="8563994066253688594928908892314570251695637864181",
        value_denominator="4480501906764632895725190",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=5,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-054d80a64e1f36a756129763ca2f1e7a140b50b04c83876ff01dd5fd497a74c5",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="33087553822039834447063841834161374382321688576",
        value_denominator="507606550755599406088755",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=6,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-b475569f6a15e97ac04e531dd813e9dcc902521c098d60d6ae4d21d53baf1395",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="22129458437198611962075707523082974663376278",
        value_denominator="466235585330384227837",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=7,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-69519fd08e31445cad84b0c17a5346b7ee9c5692e270602af9308ca6d8943bb6",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="461823962164048108560000000000000000000000000",
        value_denominator="10479085950557704780219",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=8,
        chain_id="eip155:1",
        deployment_ids=(
            "discovered-token-611597bd13daa43d01a23caa9cca6a98797c64be7fb5b2677370ddbcdeaf01ec",
        ),
        metric="onchain-total-supply-value-native",
        value_numerator="591208964484530983367688374937406614318",
        value_denominator="21093793193177765",
        quote_currency="native",
        quote_deployment_id="deployment-0001",
        observed_at="2026-09-16T16:41:59Z",
        source_id="rpc-ethereum-mainnet",
        source_asset_id=None,
    ),
    TokenRanking(
        rank=1,
        chain_id="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
        deployment_ids=("deployment-0013",),
        metric="onchain-total-supply-value-native",
        value_numerator="8934052641907075195235710143877572821100144726376448",
        value_denominator="7196706365568923421366403517072759025",
        quote_currency="native",
        quote_deployment_id="deployment-0005",
        observed_at="2026-09-16T16:57:16Z",
        source_id="rpc-solana-mainnet",
        source_asset_id=None,
    ),
)
TOKEN_RANKINGS_CONTENT_DIGEST = TOKEN_RANKINGS_METADATA.content_digest
