# Generated by registry/generate-token-rankings.mjs. Do not edit.
from __future__ import annotations

from typing import NamedTuple


class TokenRankingMetadata(NamedTuple):
    schema_version: int
    metric: str | None
    as_of: str | None
    content_digest: str
    status: str
    coverage: tuple[TokenRankingCoverage, ...]
    source_ids: tuple[str, ...]

class TokenRankingCoverage(NamedTuple):
    chain_id: str
    total_deployments: int
    ranked_deployments: int
    unranked_deployments: int
    observed_at: str | None

class TokenRanking(NamedTuple):
    rank: int
    chain_id: str
    deployment_ids: tuple[str, ...]
    metric: str
    value_numerator: str
    value_denominator: str
    quote_currency: str
    quote_deployment_id: str | None
    observed_at: str
    source_id: str
    source_asset_id: str | None

TOKEN_RANKINGS_METADATA = TokenRankingMetadata(
    schema_version=1,
    metric=None,
    as_of=None,
    content_digest="c22413bfd591ce9c0ab7cb76da1eaff4b21250a2ec13e9d46d4499c210f6fbe1",
    status="unconfigured",
    coverage=(
    ),
    source_ids=tuple([]),
)
TOKEN_RANKINGS = (
)
TOKEN_RANKINGS_CONTENT_DIGEST = TOKEN_RANKINGS_METADATA.content_digest
